"use client";

import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { measurementFields, type CheckIn } from "../lib/fitness-repository";

type Goal={id:string;metric:string;label:string;start_value:number;target_value:number;target_date:string|null;status:"active"|"completed"|"archived"};

export function GoalsArea({userId,current,onNotice}:{userId:string;current:CheckIn;onNotice:(message:string)=>void}){
  const [goals,setGoals]=useState<Goal[]>([]);const [adding,setAdding]=useState(false);const [busy,setBusy]=useState(false);
  async function load(){const {data,error}=await supabase.from("goals").select("id,metric,label,start_value,target_value,target_date,status").eq("user_id",userId).neq("status","archived").order("updated_at",{ascending:false});if(error)onNotice(error.message);else setGoals((data||[]) as Goal[])}
  useEffect(()=>{load()},[userId]);
  function currentValue(metric:string){return metric==="weight"?current.weight:current.measurements[metric as keyof typeof current.measurements]}
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const metric=String(form.get("metric"));const field=metric==="weight"?null:measurementFields.find(item=>item.key===metric);const {error}=await supabase.from("goals").insert({user_id:userId,metric,label:metric==="weight"?"Body weight":field?.label||metric,start_value:currentValue(metric),target_value:Number(form.get("target")),target_date:form.get("date")||null});setBusy(false);if(error){onNotice(error.message);return}setAdding(false);onNotice("Goal securely saved");load()}
  async function setStatus(goal:Goal,status:Goal["status"]){const {error}=await supabase.from("goals").update({status,updated_at:new Date().toISOString()}).eq("id",goal.id);if(error)onNotice(error.message);else{onNotice(status==="completed"?"Goal completed":"Goal archived");load()}}
  return <div className="content-stack goals-area"><section className="section-head"><div><p className="eyebrow">YOUR DIRECTION</p><h1>Goals.</h1></div><button className="primary" onClick={()=>setAdding(true)}>＋ Add goal</button></section><div className="soft-note"><strong>Progress, not pressure.</strong><p>Goals use measurements you record. They are personal tracking targets, not health recommendations.</p></div>{goals.length===0?<section className="empty-training"><span>◎</span><h2>Set your first target.</h2><p>Choose body weight or any recorded measurement and track the change over time.</p></section>:<section className="goal-stack">{goals.map(goal=>{const now=currentValue(goal.metric);const distance=goal.target_value-goal.start_value;const progress=distance===0?100:Math.max(0,Math.min(100,((now-goal.start_value)/distance)*100));return <article className={`goal-card ${goal.status}`} key={goal.id}><header><div><p className="eyebrow">{goal.status.toUpperCase()}</p><h2>{goal.label}</h2></div><strong>{Math.round(progress)}%</strong></header><div className="goal-track"><span style={{width:`${progress}%`}}/></div><div className="goal-values"><span>Started <b>{goal.start_value}</b></span><span>Now <b>{now}</b></span><span>Target <b>{goal.target_value}</b></span></div>{goal.target_date&&<p className="goal-date">Target date · {new Date(`${goal.target_date}T12:00:00`).toLocaleDateString("en-AU",{day:"numeric",month:"long",year:"numeric"})}</p>}<footer><button onClick={()=>setStatus(goal,"archived")}>Archive</button>{goal.status!=="completed"&&<button onClick={()=>setStatus(goal,"completed")}>Mark complete</button>}</footer></article>})}</section>}{adding&&<div className="mini-picker goal-dialog"><form onSubmit={create}><header><div><p className="eyebrow">NEW GOAL</p><h2>Choose your target</h2></div><button type="button" onClick={()=>setAdding(false)}>×</button></header><label>Measurement<select name="metric" required><option value="weight">Body weight · kg</option>{measurementFields.map(field=><option value={field.key} key={field.key}>{field.label} · cm</option>)}</select></label><label>Target value<input name="target" type="number" inputMode="decimal" min="1" step="0.1" required/></label><label>Target date <span>optional</span><input name="date" type="date"/></label><button className="primary" disabled={busy}>{busy?"Saving…":"Create goal"}</button></form></div>}</div>;
}
