"use client";

import { useEffect, useMemo, useState } from "react";
import { fitnessRepository, type CheckIn } from "../lib/fitness-repository";

const baseline = {
  date: "2026-08-25", weight: 97.5,
  measurements: [["Shoulders",132.5],["Chest",107],["Waist",93.5],["Abdomen",94],["Hips / glutes",103],["Neck",42],["Left upper arm",35],["Right upper arm",35],["Left forearm",31.5],["Right forearm",31],["Left thigh",60.5],["Right thigh",60.5],["Left calf",41.5],["Right calf",43]] as [string,number][],
};
type Tab = "Today" | "Measure" | "Train" | "Goals";

export default function Home() {
  const [tab,setTab]=useState<Tab>("Today"); const [sheetOpen,setSheetOpen]=useState(false); const [saved,setSaved]=useState(false); const [checkIns,setCheckIns]=useState<CheckIn[]>([]);
  const date=useMemo(()=>new Intl.DateTimeFormat("en-AU",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${baseline.date}T12:00:00`)),[]);
  useEffect(()=>{setCheckIns(fitnessRepository.list());if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>undefined)},[]);
  function saveCheckIn(entry: CheckIn){fitnessRepository.save(entry);setCheckIns(fitnessRepository.list());setSaved(true);setSheetOpen(false);window.setTimeout(()=>setSaved(false),2600)}
  return <main className="app-shell">
    <header className="topbar"><div className="brand-mark">P</div><div><p className="eyebrow">PHYSIQUE</p><p className="date">{date}</p></div><button className="avatar" aria-label="Open profile">RH</button></header>
    <section className="hero"><p className="eyebrow">CURRENT WEIGHT</p><div className="weight-row"><strong>{baseline.weight}</strong><span>kg</span></div><div className="target-track"><span style={{width:"72%"}}/></div><div className="target-copy"><span>Baseline recorded</span><span>Next target · 100 kg</span></div></section>
    {tab==="Today"&&<Dashboard onLog={()=>setSheetOpen(true)}/>} {tab==="Measure"&&<Measurements checkIns={checkIns}/>} {tab==="Train"&&<Placeholder kind="workouts"/>} {tab==="Goals"&&<Placeholder kind="goals"/>}
    <nav className="bottom-nav" aria-label="Primary navigation">{(["Today","Measure","Train","Goals"] as Tab[]).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}><span aria-hidden="true">{item==="Today"?"⌂":item==="Measure"?"◇":item==="Train"?"＋":"◎"}</span>{item}</button>)}</nav>
    {sheetOpen&&<LogSheet onClose={()=>setSheetOpen(false)} onSave={saveCheckIn}/>} {saved&&<div className="toast" role="status">Measurement saved on this device</div>}
  </main>;
}
function Dashboard({onLog}:{onLog:()=>void}){return <div className="content-stack"><section className="section-head"><div><p className="eyebrow">YOUR SNAPSHOT</p><h1>Built from here.</h1></div><button className="primary" onClick={onLog}>＋ Log</button></section><section className="metric-grid"><Metric value="132.5" label="Shoulders" tone="lime"/><Metric value="107" label="Chest" tone="blue"/><Metric value="93.5" label="Waist" tone="coral"/><Metric value="103" label="Hips / glutes" tone="violet"/></section><button className="plan-card"><div><p className="eyebrow">TODAY’S TRAINING</p><h2>Ready when you are</h2><p>Workouts are set up for your first program.</p></div><span>→</span></button><section className="insight-card"><p className="eyebrow">STARTING POINT</p><h2>One complete baseline</h2><p>All 14 body measurements are recorded. Your next check-in will reveal the first change.</p></section></div>}
function Metric({value,label,tone}:{value:string;label:string;tone:string}){return <article className={`metric ${tone}`}><div><strong>{value}</strong><span>cm</span></div><p>{label}</p></article>}
function Measurements({checkIns}:{checkIns:CheckIn[]}){return <div className="content-stack"><section className="section-head"><div><p className="eyebrow">BODY HISTORY</p><h1>Your baseline.</h1></div><span className="count">{checkIns.length||1} {(checkIns.length||1)===1?"entry":"entries"}</span></section>{(checkIns.length?checkIns:[{id:"baseline",date:baseline.date,weight:baseline.weight,waist:93.5}]).map((entry,index)=>{const d=new Date(`${entry.date}T12:00:00`);return <article className="history-card" key={entry.id}><div className="history-date"><strong>{d.getDate()}</strong><span>{d.toLocaleString("en-AU",{month:"short"}).toUpperCase()}<br/>{d.getFullYear()}</span></div><div><h2>{entry.weight} kg</h2><p>{index===checkIns.length-1?"Complete body check-in":`Waist · ${entry.waist} cm`}</p></div><span>✓</span></article>})}<section className="measurement-list"><p className="eyebrow">ALL BASELINE MEASUREMENTS</p>{baseline.measurements.map(([name,value])=><div key={name}><span>{name}</span><strong>{value} cm</strong></div>)}</section></div>}
function Placeholder({kind}:{kind:"workouts"|"goals"}){const workout=kind==="workouts";return <div className="content-stack"><section className="empty-state"><span className="empty-icon">{workout?"↗":"◎"}</span><p className="eyebrow">{workout?"TRAINING":"DIRECTION"}</p><h1>{workout?"Build your first workout.":"Set a target worth chasing."}</h1><p>{workout?"The structure is ready for exercises, sets, reps and personal bests.":"Track bodyweight and measurement goals, with progress visible at a glance."}</p><button className="primary">{workout?"Create workout":"Add a goal"}</button></section></div>}
function LogSheet({onClose,onSave}:{onClose:()=>void;onSave:(entry:CheckIn)=>void}){return <div className="sheet-backdrop" onClick={onClose}><form className="sheet" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);onSave({id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),weight:Number(data.get("weight")),waist:Number(data.get("waist"))})}}><div className="sheet-handle"/><div className="sheet-head"><div><p className="eyebrow">NEW CHECK-IN</p><h2>Log measurement</h2></div><button type="button" onClick={onClose} aria-label="Close">×</button></div><label>Weight <span>kg</span><input name="weight" inputMode="decimal" defaultValue="97.5" required/></label><label>Waist <span>cm</span><input name="waist" inputMode="decimal" defaultValue="93.5" required/></label><button className="primary save" type="submit">Save check-in</button></form></div>}
