"use client";
import {useEffect,useState} from "react";
import {exerciseCatalog,muscleIcons,type Exercise,type MuscleGroup} from "../lib/exercise-catalog";
import {supabase} from "../lib/supabase";

export type GeneratorProfile={experience_level:"beginner"|"intermediate"|"advanced";training_days:number;session_minutes:number;training_style:"balanced"|"strength"|"hypertrophy"|"mixed";equipment:string[];priority_muscles:string[];preferred_exercises:string[];excluded_exercises:string[];limitations_reviewed:boolean};
type Goal={label:string;goal_type:string;metric:string;priority:"primary"|"secondary";related_exercise_id:string|null};
type PlannedExercise={exerciseId:string;name:string;group:MuscleGroup;equipment:string;sets:number;reps:string;restSeconds:number};
type PlannedDay={day:number;name:string;focus:string;exercises:PlannedExercise[]};
type Draft={name:string;days:PlannedDay[];progression:string;reviewWeeks:number};
const patterns:Record<number,Array<{name:string;groups:MuscleGroup[]}>>={
1:[{name:"Full Body",groups:["Legs","Chest","Back","Glutes","Shoulders","Core"]}],
2:[{name:"Upper Body",groups:["Chest","Back","Shoulders","Arms"]},{name:"Lower Body",groups:["Legs","Glutes","Core"]}],
3:[{name:"Push",groups:["Chest","Shoulders","Arms"]},{name:"Pull",groups:["Back","Arms","Core"]},{name:"Lower Body",groups:["Legs","Glutes","Core"]}],
4:[{name:"Upper A",groups:["Chest","Back","Shoulders","Arms"]},{name:"Lower A",groups:["Legs","Glutes","Core"]},{name:"Upper B",groups:["Back","Chest","Arms","Shoulders"]},{name:"Lower B",groups:["Glutes","Legs","Core"]}],
5:[{name:"Push",groups:["Chest","Shoulders","Arms"]},{name:"Pull",groups:["Back","Arms","Core"]},{name:"Lower",groups:["Legs","Glutes","Core"]},{name:"Upper",groups:["Chest","Back","Shoulders","Arms"]},{name:"Lower + priorities",groups:["Glutes","Legs","Core"]}],
6:[{name:"Push A",groups:["Chest","Shoulders","Arms"]},{name:"Pull A",groups:["Back","Arms","Core"]},{name:"Lower A",groups:["Legs","Glutes","Core"]},{name:"Push B",groups:["Shoulders","Chest","Arms"]},{name:"Pull B",groups:["Back","Arms","Core"]},{name:"Lower B",groups:["Glutes","Legs","Core"]}],
7:[{name:"Push A",groups:["Chest","Shoulders","Arms"]},{name:"Pull A",groups:["Back","Arms"]},{name:"Lower A",groups:["Legs","Glutes","Core"]},{name:"Upper",groups:["Chest","Back","Shoulders","Arms"]},{name:"Lower B",groups:["Glutes","Legs","Core"]},{name:"Full Body",groups:["Legs","Chest","Back","Glutes"]},{name:"Conditioning + Core",groups:["Cardio","Core"]}]};
const toGroup=(name:string):MuscleGroup|null=>{const value=name.toLowerCase();if(/quad|hamstring|thigh|calf|leg/.test(value))return "Legs";if(/glute|hip/.test(value))return "Glutes";if(/chest/.test(value))return "Chest";if(/back/.test(value))return "Back";if(/shoulder/.test(value))return "Shoulders";if(/arm|forearm|bicep|tricep/.test(value))return "Arms";if(/core|waist|abdomen/.test(value))return "Core";return null};
const allowed=(exercise:Exercise,profile:GeneratorProfile)=>profile.equipment.includes("Commercial gym")||profile.equipment.some(item=>({Barbell:"Barbell & rack",Dumbbell:"Dumbbells",Cable:"Cables",Machine:"Machines",Band:"Bands",Bodyweight:"Bodyweight"}[exercise.equipment]===item));
function build(profile:GeneratorProfile,goals:Goal[]):Draft{const available=exerciseCatalog.filter(exercise=>allowed(exercise,profile)&&!profile.excluded_exercises.some(item=>exercise.name.toLowerCase().includes(item.toLowerCase())));const preferred=new Set(profile.preferred_exercises.map(item=>item.toLowerCase()));const priorities=[...profile.priority_muscles.map(toGroup),...goals.map(goal=>goal.goal_type==="body_measurement"?toGroup(goal.metric):null)].filter(Boolean) as MuscleGroup[];const schedule=patterns[profile.training_days]||patterns[3];const count=profile.session_minutes<=40?4:profile.session_minutes<=65?5:6;const used=new Set<string>();const sets=profile.experience_level==="beginner"?2:profile.experience_level==="advanced"?4:3;const reps=profile.training_style==="strength"?"4–6":profile.training_style==="hypertrophy"?"8–12":"6–10";const choose=(group:MuscleGroup)=>{const pool=available.filter(e=>e.group===group).sort((a,b)=>Number(preferred.has(b.name.toLowerCase()))-Number(preferred.has(a.name.toLowerCase()))||Number(used.has(a.id))-Number(used.has(b.id)));const exercise=pool[0]||available.find(e=>!used.has(e.id));if(exercise)used.add(exercise.id);return exercise};const days=schedule.map((item,index)=>{const exercises:PlannedExercise[]=[];for(const group of [...priorities.filter(g=>item.groups.includes(g)),...item.groups]){if(exercises.length>=count)break;const exercise=choose(group);if(!exercise||exercises.some(e=>e.exerciseId===exercise.id))continue;exercises.push({exerciseId:exercise.id,name:exercise.name,group:exercise.group,equipment:exercise.equipment,sets,reps:exercise.tracking==="duration"?"30–60 sec":exercise.tracking==="distance"?"steady effort":reps,restSeconds:exercise.restSeconds||60})}return {day:index+1,name:item.name,focus:item.groups.join(" · "),exercises}});return {name:`${profile.training_days}-day ${profile.training_style} draft`,days,progression:"When every working set reaches the top of its rep range with controlled technique, add the smallest practical amount of load next time. If performance falls, keep the load steady rather than forcing an increase.",reviewWeeks:4}}

export function ProgramGenerator({userId,profile,ready,onNotice}:{userId:string;profile:GeneratorProfile|null;ready:boolean;onNotice:(message:string)=>void}){const [draft,setDraft]=useState<Draft|null>(null);const [why,setWhy]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [expanded,setExpanded]=useState<number|null>(0);useEffect(()=>{supabase.from("program_drafts").select("plan,rationale").eq("user_id",userId).maybeSingle().then(({data})=>{if(data){setDraft(data.plan as Draft);setWhy(data.rationale as string[])}})},[userId]);async function generate(){if(!profile||!ready)return;setBusy(true);const {data:goals,error}=await supabase.from("goals").select("label,goal_type,metric,priority,related_exercise_id").eq("user_id",userId).eq("status","active").order("priority");if(error){setBusy(false);onNotice(error.message);return}const next=build(profile,(goals||[]) as Goal[]);const rationale=[`Built around ${profile.training_days} training days of about ${profile.session_minutes} minutes.`,"Uses only the equipment selected in your program profile.",profile.priority_muscles.length?`Gives earlier attention to ${profile.priority_muscles.join(", ")}.`:"Uses a balanced muscle-group order.",`Working volume reflects your ${profile.experience_level} experience level.`];const {error:saveError}=await supabase.from("program_drafts").upsert({user_id:userId,status:"draft",plan:next,rationale,generated_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id"});setBusy(false);if(saveError){onNotice(saveError.message);return}setDraft(next);setWhy(rationale);setExpanded(1);onNotice("Draft program generated and securely saved")}
if(!ready)return <section className="generator-locked"><span>⌁</span><div><strong>Program generator locked</strong><p>Complete all five readiness items to create a sensible draft.</p></div></section>;
if(!draft)return <section className="program-generator"><p className="eyebrow">RULE-BASED GENERATOR · V0.11A</p><h2>Create your first draft.</h2><p>Physique will combine your goal, schedule, equipment and preferences using controlled training rules.</p><button className="primary" onClick={generate} disabled={busy}>{busy?"Building…":"Generate draft program"}</button><small>No AI service is used in this version. Nothing will enter your active workout schedule yet.</small></section>;
return <section className="program-draft"><header><div><p className="eyebrow">SAVED DRAFT · NOT ACTIVE</p><h2>{draft.name}</h2></div><button onClick={generate} disabled={busy} aria-label="Regenerate draft">{busy?"…":"↻"}</button></header><div className="draft-summary"><span><b>{draft.days.length}</b> days</span><span><b>{draft.days.reduce((n,d)=>n+d.exercises.reduce((s,e)=>s+e.sets,0),0)}</b> sets / week</span><span><b>{draft.reviewWeeks}</b> week review</span></div><div className="draft-days">{draft.days.map(day=><article key={day.day}><button onClick={()=>setExpanded(expanded===day.day?null:day.day)}><span>DAY {day.day}</span><div><strong>{day.name}</strong><small>{day.exercises.length} exercises · {day.focus}</small></div><b>{expanded===day.day?"−":"＋"}</b></button>{expanded===day.day&&<div className="draft-exercises">{day.exercises.map((exercise,index)=><div key={exercise.exerciseId}><span>{muscleIcons[exercise.group]}</span><div><strong>{index+1}. {exercise.name}</strong><small>{exercise.equipment}</small></div><p><b>{exercise.sets}</b> × {exercise.reps}<small>{Math.round(exercise.restSeconds/30)*0.5} min rest</small></p></div>)}</div>}</article>)}</div><div className="draft-progression"><strong>Progression rule</strong><p>{draft.progression}</p></div><details><summary>Why this draft looks this way</summary>{why.map(item=><p key={item}>✓ {item}</p>)}</details><div className="goal-boundary"><strong>Review comes next</strong><p>This is a general training draft, not medical advice. v0.11b will add exercise replacement, reordering and explicit activation.</p></div></section>}
