"use client";

import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Supplement={id:string;name:string;brand:string|null;dose_value:number;dose_unit:string;scheduled_time:string;active:boolean;notes:string|null};
type Log={supplement_id:string;status:"taken"|"skipped"};
export type SupplementSummary={total:number;recorded:number;next:string|null};

const today=()=>new Date().toISOString().slice(0,10);
export async function loadSupplementSummary(userId:string):Promise<SupplementSummary>{const [{data:supplements},{data:logs}]=await Promise.all([supabase.from("supplements").select("id,name,scheduled_time").eq("user_id",userId).eq("active",true).order("scheduled_time"),supabase.from("supplement_logs").select("supplement_id").eq("user_id",userId).eq("scheduled_on",today())]);const done=new Set((logs||[]).map(log=>log.supplement_id));const next=(supplements||[]).find(item=>!done.has(item.id));return {total:supplements?.length||0,recorded:done.size,next:next?`${next.name} · ${String(next.scheduled_time).slice(0,5)}`:null}}

export function SupplementsArea({userId,onSummary,onNotice}:{userId:string;onSummary:(summary:SupplementSummary)=>void;onNotice:(message:string)=>void}){
  const [items,setItems]=useState<Supplement[]>([]);const [logs,setLogs]=useState<Log[]>([]);const [adding,setAdding]=useState(false);const [busy,setBusy]=useState(false);
  async function load(){const [{data:supplements,error},{data:records}]=await Promise.all([supabase.from("supplements").select("id,name,brand,dose_value,dose_unit,scheduled_time,active,notes").eq("user_id",userId).order("scheduled_time"),supabase.from("supplement_logs").select("supplement_id,status").eq("user_id",userId).eq("scheduled_on",today())]);if(error){onNotice(error.message);return}setItems((supplements||[]) as Supplement[]);setLogs((records||[]) as Log[]);onSummary(await loadSupplementSummary(userId))}
  useEffect(()=>{load()},[userId]);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const {error}=await supabase.from("supplements").insert({user_id:userId,name:String(form.get("name")),brand:String(form.get("brand")||"")||null,dose_value:Number(form.get("dose")),dose_unit:String(form.get("unit")),scheduled_time:String(form.get("time")),notes:String(form.get("notes")||"")||null});setBusy(false);if(error){onNotice(error.message);return}setAdding(false);onNotice("Supplement record securely saved");load()}
  async function record(item:Supplement,status:Log["status"]){const existing=logs.find(log=>log.supplement_id===item.id);const result=existing?await supabase.from("supplement_logs").update({status,recorded_at:new Date().toISOString()}).eq("supplement_id",item.id).eq("scheduled_on",today()):await supabase.from("supplement_logs").insert({user_id:userId,supplement_id:item.id,scheduled_on:today(),status});if(result.error)onNotice(result.error.message);else{onNotice(`${item.name} marked ${status}`);load()}}
  async function toggle(item:Supplement){const {error}=await supabase.from("supplements").update({active:!item.active,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)onNotice(error.message);else load()}
  const active=items.filter(item=>item.active);const recorded=active.filter(item=>logs.some(log=>log.supplement_id===item.id)).length;
  return <div className="content-stack supps-area"><section className="section-head"><div><p className="eyebrow">PERSONAL RECORDS</p><h1>Supplements.</h1></div><button className="primary" onClick={()=>setAdding(true)}>＋ Add</button></section><section className="supp-summary"><div><strong>{recorded}</strong><span>of {active.length}</span></div><p>recorded today</p></section><div className="medical-boundary"><strong>Logging only</strong><p>Physique records the details you enter. It does not recommend products or dosages and does not provide medical advice.</p></div>{items.length===0?<section className="empty-training"><span>◉</span><h2>Your list is empty.</h2><p>Add supplements you already use to create a personal schedule.</p></section>:<section className="supp-stack">{items.map(item=>{const log=logs.find(entry=>entry.supplement_id===item.id);return <article className={`supp-card ${!item.active?"paused":""}`} key={item.id}><header><div className="supp-time">{item.scheduled_time.slice(0,5)}</div><div><h2>{item.name}</h2><p>{item.dose_value} {item.dose_unit}{item.brand?` · ${item.brand}`:""}</p></div><button onClick={()=>toggle(item)}>{item.active?"Pause":"Resume"}</button></header>{item.notes&&<p className="supp-notes">{item.notes}</p>}{item.active&&<footer><button className={log?.status==="skipped"?"selected":""} onClick={()=>record(item,"skipped")}>Skip</button><button className={log?.status==="taken"?"taken selected":"taken"} onClick={()=>record(item,"taken")}>✓ Taken</button></footer>}</article>})}</section>}{adding&&<div className="mini-picker supp-dialog"><form onSubmit={create}><header><div><p className="eyebrow">NEW PERSONAL RECORD</p><h2>Add supplement</h2></div><button type="button" onClick={()=>setAdding(false)}>×</button></header><label>Name<input name="name" maxLength={120} required/></label><label>Brand <span>optional</span><input name="brand" maxLength={120}/></label><div className="dose-fields"><label>Dose<input name="dose" type="number" min="0.001" step="any" inputMode="decimal" required/></label><label>Unit<select name="unit">{["mg","g","mcg","ml","capsule","capsules","tablet","tablets","scoop","scoops"].map(unit=><option key={unit}>{unit}</option>)}</select></label></div><label>Scheduled time<input name="time" type="time" required/></label><label>Personal notes <span>optional</span><textarea name="notes" rows={3} maxLength={1000}/></label><button className="primary" disabled={busy}>{busy?"Saving…":"Save personal record"}</button></form></div>}</div>;
}
