"use client";

import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Supplement={id:string;name:string;brand:string|null;dose_value:number;dose_unit:string;scheduled_time:string;scheduled_weekdays:number[];active:boolean;notes:string|null;reminder_enabled:boolean;follow_up_minutes:number|null};
type Log={supplement_id:string;scheduled_on?:string;status:"taken"|"skipped"};
export type SupplementSummary={total:number;recorded:number;next:string|null};
const localDate=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const today=()=>localDate();
const sevenDaysAgo=()=>{const date=new Date();date.setDate(date.getDate()-6);return localDate(date)};
const days=[{value:1,short:"M",label:"Monday"},{value:2,short:"T",label:"Tuesday"},{value:3,short:"W",label:"Wednesday"},{value:4,short:"T",label:"Thursday"},{value:5,short:"F",label:"Friday"},{value:6,short:"S",label:"Saturday"},{value:0,short:"S",label:"Sunday"}];
const daySummary=(values:number[])=>values.length===7?"Every day":values.length===5&&[1,2,3,4,5].every(day=>values.includes(day))?"Weekdays":days.filter(day=>values.includes(day.value)).map(day=>day.label.slice(0,3)).join(", ");

export async function loadSupplementSummary(userId:string):Promise<SupplementSummary>{
  const [{data:supplements},{data:logs}]=await Promise.all([supabase.from("supplements").select("id,name,scheduled_time,scheduled_weekdays").eq("user_id",userId).eq("active",true).order("scheduled_time"),supabase.from("supplement_logs").select("supplement_id").eq("user_id",userId).eq("scheduled_on",today())]);
  const todaysItems=(supplements||[]).filter(item=>(item.scheduled_weekdays as number[]).includes(new Date().getDay())),done=new Set((logs||[]).map(log=>log.supplement_id)),next=todaysItems.find(item=>!done.has(item.id));
  return {total:todaysItems.length,recorded:todaysItems.filter(item=>done.has(item.id)).length,next:next?`${next.name} · ${String(next.scheduled_time).slice(0,5)}`:null};
}

export function SupplementsArea({userId,onSummary,onNotice}:{userId:string;onSummary:(summary:SupplementSummary)=>void;onNotice:(message:string)=>void}){
  const [items,setItems]=useState<Supplement[]>([]),[logs,setLogs]=useState<Log[]>([]),[weekLogs,setWeekLogs]=useState<Log[]>([]);
  const [editing,setEditing]=useState<Supplement|"new"|null>(null),[busy,setBusy]=useState(false);
  async function load(){
    const [{data:supplements,error},{data:records},{data:history}]=await Promise.all([
      supabase.from("supplements").select("id,name,brand,dose_value,dose_unit,scheduled_time,scheduled_weekdays,active,notes,reminder_enabled,follow_up_minutes").eq("user_id",userId).order("scheduled_time"),
      supabase.from("supplement_logs").select("supplement_id,status").eq("user_id",userId).eq("scheduled_on",today()),
      supabase.from("supplement_logs").select("supplement_id,status,scheduled_on").eq("user_id",userId).gte("scheduled_on",sevenDaysAgo())
    ]);
    if(error){onNotice(error.message);return}setItems((supplements||[]) as Supplement[]);setLogs((records||[]) as Log[]);setWeekLogs((history||[]) as Log[]);onSummary(await loadSupplementSummary(userId));
  }
  useEffect(()=>{load()},[userId]);
  async function save(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);
    const values={user_id:userId,name:String(form.get("name")),brand:String(form.get("brand")||"")||null,dose_value:Number(form.get("dose")),dose_unit:String(form.get("unit")),scheduled_time:String(form.get("time")),scheduled_weekdays:form.getAll("weekdays").map(Number),notes:String(form.get("notes")||"")||null,reminder_enabled:form.get("reminder")==="on",follow_up_minutes:form.get("followUp")?Number(form.get("followUp")):null,updated_at:new Date().toISOString()};
    const result=editing!=="new"&&editing?await supabase.from("supplements").update(values).eq("id",editing.id).eq("user_id",userId):await supabase.from("supplements").insert(values);
    setBusy(false);if(result.error){onNotice(result.error.message);return}const created=editing==="new";setEditing(null);onNotice(created?"Supplement schedule securely saved":"Supplement schedule updated");load();
  }
  async function record(item:Supplement,status:Log["status"]){const existing=logs.find(log=>log.supplement_id===item.id);const result=existing?await supabase.from("supplement_logs").update({status,recorded_at:new Date().toISOString()}).eq("user_id",userId).eq("supplement_id",item.id).eq("scheduled_on",today()):await supabase.from("supplement_logs").insert({user_id:userId,supplement_id:item.id,scheduled_on:today(),status});if(result.error)onNotice(result.error.message);else{onNotice(`${item.name} marked ${status}`);load()}}
  async function toggle(item:Supplement){const {error}=await supabase.from("supplements").update({active:!item.active,updated_at:new Date().toISOString()}).eq("id",item.id).eq("user_id",userId);if(error)onNotice(error.message);else load()}
  const active=items.filter(item=>item.active),dueToday=active.filter(item=>item.scheduled_weekdays.includes(new Date().getDay())),recorded=dueToday.filter(item=>logs.some(log=>log.supplement_id===item.id)).length;
  const expected=Array.from({length:7},(_,offset)=>{const date=new Date();date.setDate(date.getDate()-offset);return active.filter(item=>item.scheduled_weekdays.includes(date.getDay())).length}).reduce((total,count)=>total+count,0);
  const taken=weekLogs.filter(log=>log.status==="taken"&&active.some(item=>item.id===log.supplement_id)).length,skipped=weekLogs.filter(log=>log.status==="skipped"&&active.some(item=>item.id===log.supplement_id)).length,adherence=expected?Math.round(taken/expected*100):0;
  return <div className="content-stack supps-area"><section className="section-head"><div><p className="eyebrow">PERSONAL RECORDS · V0.14B.1</p><h1>Supplements.</h1></div><button className="primary" onClick={()=>setEditing("new")}>＋ Add</button></section><section className="supp-summary"><div><strong>{recorded}</strong><span>of {dueToday.length}</span></div><p>scheduled today</p></section>{active.length>0&&<section className="supp-adherence"><div><p className="eyebrow">LAST 7 DAYS</p><strong>{adherence}%</strong><span>taken as scheduled</span></div><p><b>{taken}</b> taken · <b>{skipped}</b> skipped · <b>{Math.max(0,expected-taken-skipped)}</b> unrecorded</p><small>Unrecorded means no Taken or Skip choice was saved. It is not a medical assessment.</small></section>}<div className="medical-boundary"><strong>Logging only</strong><p>Physique records the details you enter. It does not recommend products or dosages and does not provide medical advice.</p></div>{items.length===0?<section className="empty-training"><span>◉</span><h2>Your list is empty.</h2><p>Add supplements you already use to create a personal schedule.</p></section>:<section className="supp-stack">{items.map(item=>{const log=logs.find(entry=>entry.supplement_id===item.id);return <article className={`supp-card ${!item.active?"paused":""}`} key={item.id}><header><div className="supp-time">{item.scheduled_time.slice(0,5)}</div><div><h2>{item.name}</h2><p>{item.dose_value} {item.dose_unit}{item.brand?` · ${item.brand}`:""}</p></div><button onClick={()=>setEditing(item)}>Edit</button></header><div className="supp-reminder-state"><span>{item.reminder_enabled?"◉":"○"}</span><small>{item.reminder_enabled?`Reminder at ${item.scheduled_time.slice(0,5)}${item.follow_up_minutes?` + follow-up after ${item.follow_up_minutes} min`:""}`:"Reminders off for this item"}</small></div><small className="supp-days">{daySummary(item.scheduled_weekdays)}</small>{item.notes&&<p className="supp-notes">{item.notes}</p>}<div className="supp-card-controls"><button onClick={()=>toggle(item)}>{item.active?"Pause":"Resume"}</button>{item.active&&<><button className={log?.status==="skipped"?"selected":""} onClick={()=>record(item,"skipped")}>Skip</button><button className={log?.status==="taken"?"taken selected":"taken"} onClick={()=>record(item,"taken")}>✓ Taken</button></>}</div></article>})}</section>}{editing&&<SupplementEditor item={editing==="new"?null:editing} busy={busy} onClose={()=>setEditing(null)} onSave={save}/>}</div>;
}

function SupplementEditor({item,busy,onClose,onSave}:{item:Supplement|null;busy:boolean;onClose:()=>void;onSave:(event:React.FormEvent<HTMLFormElement>)=>void}){
  const [reminder,setReminder]=useState(item?.reminder_enabled??true),[selectedDays,setSelectedDays]=useState<number[]>(item?.scheduled_weekdays??[0,1,2,3,4,5,6]);
  return <div className="mini-picker supp-dialog"><form onSubmit={onSave}><header><div><p className="eyebrow">{item?"EDIT PERSONAL RECORD":"NEW PERSONAL RECORD"}</p><h2>{item?"Update supplement":"Add supplement"}</h2></div><button type="button" onClick={onClose}>×</button></header><label>Name<input name="name" maxLength={120} defaultValue={item?.name} required/></label><label>Brand <span>optional</span><input name="brand" maxLength={120} defaultValue={item?.brand||""}/></label><div className="dose-fields"><label>Dose<input name="dose" type="number" min="0.001" step="any" inputMode="decimal" defaultValue={item?.dose_value} required/></label><label>Unit<select name="unit" defaultValue={item?.dose_unit||"mg"}>{["mg","g","mcg","ml","capsule","capsules","tablet","tablets","scoop","scoops"].map(unit=><option key={unit}>{unit}</option>)}</select></label></div><label>Scheduled time<input name="time" type="time" defaultValue={item?.scheduled_time.slice(0,5)} required/></label><fieldset className="supp-weekdays"><legend>Days taken</legend><div>{days.map(day=><label key={day.value} title={day.label}><input name="weekdays" type="checkbox" value={day.value} checked={selectedDays.includes(day.value)} onChange={event=>setSelectedDays(current=>event.target.checked?[...current,day.value]:current.filter(value=>value!==day.value))}/><span>{day.short}</span></label>)}</div><small>{selectedDays.length?daySummary(selectedDays):"Choose at least one day"}</small></fieldset><label className="supp-reminder-toggle"><span><strong>Remind me</strong><small>Requires separate device notification opt-in</small></span><input name="reminder" type="checkbox" checked={reminder} onChange={event=>setReminder(event.target.checked)}/></label>{reminder&&<label>Follow-up if still unrecorded <span>optional</span><select name="followUp" defaultValue={item?.follow_up_minutes||""}><option value="">No follow-up</option><option value="15">After 15 minutes</option><option value="30">After 30 minutes</option><option value="60">After 1 hour</option><option value="90">After 90 minutes</option><option value="120">After 2 hours</option></select></label>}<label>Personal notes <span>optional</span><textarea name="notes" rows={3} maxLength={1000} defaultValue={item?.notes||""}/></label><button className="primary" disabled={busy||selectedDays.length===0}>{busy?"Saving…":item?"Save changes":"Save personal record"}</button></form></div>;
}
