"use client";
import {useEffect,useMemo,useState} from "react";
import {exerciseCatalog,muscleIcons,starterTemplates,type Exercise,type MuscleGroup} from "../lib/exercise-catalog";
import {workoutRepository,type ActiveExercise,type WorkoutHistory} from "../lib/workout-repository";

type View="Start"|"Library"|"History";
export function WorkoutArea({userId,onNotice}:{userId:string;onNotice:(message:string)=>void}){
 const [view,setView]=useState<View>("Start");const [active,setActive]=useState<{name:string;startedAt:string;items:ActiveExercise[]}|null>(()=>{if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem("physique.active-workout.v1")||"null")}catch{return null}});const [history,setHistory]=useState<WorkoutHistory[]>([]);
 useEffect(()=>{workoutRepository.history().then(setHistory).catch(()=>undefined)},[]);
 useEffect(()=>{if(active)localStorage.setItem("physique.active-workout.v1",JSON.stringify(active));else localStorage.removeItem("physique.active-workout.v1")},[active]);
 function begin(name:string,ids:string[]){setActive({name,startedAt:new Date().toISOString(),items:ids.map(id=>workoutRepository.exercise(id)).filter(Boolean).map(exercise=>({exercise:exercise!,sets:[{weight:0,reps:10,done:false},{weight:0,reps:10,done:false},{weight:0,reps:10,done:false}]}))})}
 async function finish(){if(!active)return;try{await workoutRepository.finish(userId,active.name,active.items,active.startedAt);onNotice("Workout completed and synced");setActive(null);setHistory(await workoutRepository.history());setView("History")}catch(error){onNotice(error instanceof Error?error.message:"Unable to save workout")}}
 if(active)return <ActiveWorkout session={active} setSession={setActive} onFinish={finish} onCancel={()=>setActive(null)}/>;
 return <div className="content-stack workout-area"><section className="section-head"><div><p className="eyebrow">TRAINING</p><h1>Build the work.</h1></div><button className="primary" onClick={()=>begin("Quick workout",[])}>＋ Start</button></section><div className="segmented" role="tablist">{(["Start","Library","History"] as View[]).map(v=><button key={v} role="tab" aria-selected={view===v} className={view===v?"selected":""} onClick={()=>setView(v)}>{v}</button>)}</div>
 {view==="Start"&&<TemplateStart onBegin={begin}/>} {view==="Library"&&<ExerciseLibrary onBegin={exercise=>begin(exercise.name,[exercise.id])}/>} {view==="History"&&<WorkoutHistoryList history={history}/>}
 </div>
}
function TemplateStart({onBegin}:{onBegin:(name:string,ids:string[])=>void}){return <><section className="training-summary"><div><p className="eyebrow">READY WHEN YOU ARE</p><h2>Choose a session.</h2></div><strong>{exerciseCatalog.length}<small> exercises</small></strong></section><section className="template-stack">{starterTemplates.map((t,index)=><button className="template-card" key={t.name} onClick={()=>onBegin(t.name,t.exerciseIds)}><span className={"template-icon tone-"+index}>{index===0?"🍑":index===1?"🫀":index===2?"🦅":"⚡"}</span><div><h2>{t.name}</h2><p>{t.exerciseIds.length} exercises · about {t.exerciseIds.length*10} min</p></div><b>›</b></button>)}</section><div className="soft-note"><strong>Gym-proof logging</strong><p>Your active session stays on screen while you enter each set, then syncs securely when completed.</p></div></>}
function ExerciseLibrary({onBegin}:{onBegin:(e:Exercise)=>void}){const [query,setQuery]=useState("");const [group,setGroup]=useState<MuscleGroup|null>(null);const filtered=useMemo(()=>exerciseCatalog.filter(e=>(!group||e.group===group)&&(!query||[e.name,e.equipment,...(e.aliases||[])].join(" ").toLowerCase().includes(query.toLowerCase()))),[query,group]);return <><label className="exercise-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search exercises or RDL…"/></label><div className="muscle-filters"><button className={!group?"selected":""} onClick={()=>setGroup(null)}>All</button>{Object.entries(muscleIcons).map(([name,icon])=><button className={group===name?"selected":""} onClick={()=>setGroup(name as MuscleGroup)} key={name}>{icon} {name}</button>)}</div><p className="library-count">{filtered.length} exercises</p><section className="exercise-list">{filtered.map(e=><button key={e.id} onClick={()=>onBegin(e)}><span>{muscleIcons[e.group]}</span><div><strong>{e.name}</strong><small>{e.equipment} · {e.restSeconds?e.restSeconds/60+" min rest":"tracked cardio"}</small></div><b>＋</b></button>)}</section></>}
function ActiveWorkout({session,setSession,onFinish,onCancel}:{session:{name:string;startedAt:string;items:ActiveExercise[]};setSession:(s:any)=>void;onFinish:()=>void;onCancel:()=>void}){const [adding,setAdding]=useState(false);const done=session.items.reduce((n,i)=>n+i.sets.filter(s=>s.done).length,0);function updateSet(ei:number,si:number,key:"weight"|"reps",value:number){setSession({...session,items:session.items.map((item,i)=>i!==ei?item:{...item,sets:item.sets.map((set,s)=>s!==si?set:{...set,[key]:value})})})}function toggle(ei:number,si:number){setSession({...session,items:session.items.map((item,i)=>i!==ei?item:{...item,sets:item.sets.map((set,s)=>s!==si?set:{...set,done:!set.done})})})}function add(exercise:Exercise){setSession({...session,items:[...session.items,{exercise,sets:[{weight:0,reps:10,done:false},{weight:0,reps:10,done:false},{weight:0,reps:10,done:false}]}]});setAdding(false)}return <div className="content-stack active-workout"><section className="active-head"><button onClick={onCancel}>×</button><div><p className="eyebrow">ACTIVE WORKOUT</p><h1>{session.name}</h1></div><button className="finish-button" onClick={onFinish} disabled={!done}>Finish</button></section><div className="active-stats"><span><strong>{session.items.length}</strong> exercises</span><span><strong>{done}</strong> sets done</span></div>{session.items.map((item,ei)=><article className="logging-card" key={item.exercise.id}><header><span>{muscleIcons[item.exercise.group]}</span><div><h2>{item.exercise.name}</h2><p>{item.exercise.restSeconds?item.exercise.restSeconds/60+" min suggested rest":"Tracked cardio"}</p></div></header><div className="set-row set-labels"><span>Set</span><span>kg</span><span>Reps</span><span>Done</span></div>{item.sets.map((set,si)=><div className={"set-row "+(set.done?"complete":"")} key={si}><strong>{si+1}</strong><input type="number" inputMode="decimal" min="0" step=".5" value={set.weight} onChange={e=>updateSet(ei,si,"weight",Number(e.target.value))}/><input type="number" inputMode="numeric" min="0" value={set.reps} onChange={e=>updateSet(ei,si,"reps",Number(e.target.value))}/><button onClick={()=>toggle(ei,si)} aria-label={set.done?"Mark incomplete":"Mark complete"}>{set.done?"✓":"○"}</button></div>)}</article>)}<button className="add-exercise" onClick={()=>setAdding(true)}>＋ Add exercise</button>{adding&&<div className="mini-picker"><header><h2>Add exercise</h2><button onClick={()=>setAdding(false)}>×</button></header>{exerciseCatalog.slice(0,40).map(e=><button key={e.id} onClick={()=>add(e)}>{muscleIcons[e.group]} {e.name}</button>)}</div>}</div>}
function WorkoutHistoryList({history}:{history:WorkoutHistory[]}){if(!history.length)return <section className="empty-training"><span>↗</span><h2>Your training history starts here.</h2><p>Complete your first workout to see volume, exercises and session details.</p></section>;return <section className="workout-history">{history.map(w=><article key={w.id}><div><p className="eyebrow">{new Date(w.startedAt).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"})}</p><h2>{w.name}</h2><p>{w.exerciseNames.join(" · ")}</p></div><footer><span>{w.setCount} sets</span><strong>{Math.round(w.volume).toLocaleString()} kg volume</strong></footer></article>)}</section>}
