"use client";
import {useEffect,useState} from 'react';
import {planner,todayDate,monthDates,calendarStatus,type CalendarEntry} from '../lib/workout-planner';
import type {WorkoutTemplate} from '../lib/workout-repository';
import {muscleIcons} from '../lib/exercise-catalog';
import './workout-planner.css';
type Props={cards:WorkoutTemplate[];mode:'cards'|'calendar';onStart:(card:WorkoutTemplate,entry?:CalendarEntry)=>void;onEdit:(card:WorkoutTemplate)=>void;onChanged:()=>void;onError:(message:string)=>void};
const message=(error:unknown)=>error instanceof Error?error.message:(error as {message?:string})?.message||'Unable to save. Please try again.';
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'short'});
export function WorkoutPlanner({cards,mode,onStart,onEdit,onChanged,onError}:Props){
 const today=todayDate();const [month,setMonth]=useState(today.slice(0,7)),[selected,setSelected]=useState(today),[entries,setEntries]=useState<CalendarEntry[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [detail,setDetail]=useState<WorkoutTemplate|null>(null),[choice,setChoice]=useState<WorkoutTemplate|null>(null),[selectedCard,setSelectedCard]=useState(''),[weeks,setWeeks]=useState(1),[moveDate,setMoveDate]=useState('');
 const dates=monthDates(month),entry=entries.find(e=>e.scheduled_on===selected),todayEntry=entries.find(e=>e.scheduled_on===today),recommended=cards.find(c=>c.id===todayEntry?.card_id);
 async function refresh(){setLoading(true);try{const start=dates[0]<today?dates[0]:today,end=dates[41]>today?dates[41]:today;setEntries(await planner.entries(start,end));setError('')}catch(e){setError(message(e))}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[month,cards,today]);
 useEffect(()=>{setSelectedCard(entry?.card_id||'');setWeeks(1);setMoveDate('')},[selected,entry?.id,entry?.card_id]);
 async function act(action:()=>Promise<unknown>){setBusy(true);try{await action();await refresh();onChanged()}catch(e){const text=message(e);setError(text);onError(text)}finally{setBusy(false)}}
 function requestStart(card:WorkoutTemplate){if(todayEntry?.status==='planned'&&todayEntry.kind==='workout'&&todayEntry.card_id===card.id){onStart(card,todayEntry);return}if(todayEntry&&todayEntry.status==='planned'){setChoice(card);return}onStart(card)}
 function navigateMonth(delta:number){const d=new Date(month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+delta);setMonth(d.toISOString().slice(0,7))}
 return <div className="planner-stack">
  {error&&<div className="planner-error" role="alert">{error}<button onClick={()=>void refresh()}>Retry</button></div>}
  {mode==='cards'&&<>
   <section className="today-workout"><p className="eyebrow">TODAY · {dateLabel(today)}</p><h2>{loading?'Loading your plan…':todayEntry?.status==='completed'?'Today’s planned workout is complete':todayEntry?.status==='skipped'?'Today’s workout was skipped':todayEntry?.kind==='rest'?'Planned rest day':recommended?.name||'No workout scheduled'}</h2><p>{recommended&&todayEntry?.status==='planned'?`${recommended.items.length} exercises · Your calendar recommendation`:'Pick any saved workout below, or plan your next session in Calendar.'}</p>{recommended&&todayEntry?.status==='planned'&&<button className="primary" disabled={busy||loading} onClick={()=>onStart(recommended,todayEntry)}>Start recommended workout</button>}</section>
   <p className="library-count">Saved workout cards · {cards.length}</p>
   {!cards.length&&!loading&&<div className="soft-note">Use Build to save your first workout card.</div>}
   <div className="saved-workout-grid">{cards.map(card=><article className="saved-workout-card" key={card.id}><p className="eyebrow">{[...new Set(card.items.map(i=>i.exercise.group))].join(' · ')}</p><h2>{card.name}</h2><p>{card.items.length} exercises · {card.items.reduce((n,i)=>n+i.targetSets,0)} working sets</p><ul>{card.items.slice(0,3).map((item,i)=><li key={i}>{muscleIcons[item.exercise.group]} {item.exercise.name}<span>{item.targetSets} × {item.targetReps}</span></li>)}</ul>{card.items.length>3&&<small>+ {card.items.length-3} more exercises</small>}<div className="planner-actions"><button onClick={()=>setDetail(card)}>View workout</button><button className="primary" disabled={loading||busy} onClick={()=>requestStart(card)}>Start</button></div></article>)}</div>
  </>}
  {mode==='calendar'&&<section className="workout-calendar"><header><button aria-label="Previous month" onClick={()=>navigateMonth(-1)}>‹</button><h2>{new Date(month+'-01T12:00:00').toLocaleDateString('en-AU',{month:'long',year:'numeric'})}</h2><button aria-label="Next month" onClick={()=>navigateMonth(1)}>›</button></header><button className="calendar-today" onClick={()=>{setMonth(today.slice(0,7));setSelected(today)}}>Go to today</button><div className="calendar-weekdays">{['M','T','W','T','F','S','S'].map((day,i)=><span key={i}>{day}</span>)}</div><div className="calendar-grid">{dates.map(date=>{const day=entries.find(e=>e.scheduled_on===date),status=day?calendarStatus(day,today):'empty';return <button key={date} aria-label={`${dateLabel(date)} · ${day?.kind==='workout'?cards.find(c=>c.id===day.card_id)?.name||'Workout':status} · ${status}`} aria-pressed={selected===date} className={`${date.slice(0,7)!==month?'outside':''} ${date===today?'is-today':''} ${selected===date?'selected':''} ${status}`} onClick={()=>setSelected(date)}><b>{Number(date.slice(-2))}</b><span>{status==='completed'?'✓':status==='rest'?'Rest':status==='missed'?'Missed':status==='skipped'?'Skip':status==='moved'?'Moved':status==='planned'?'Train':''}</span></button>})}</div><p className="calendar-legend">Train · Rest · ✓ Complete · Missed stays on its original date</p>
   <div className="calendar-day-editor"><p className="eyebrow">{dateLabel(selected)}</p><h3>{entry?.kind==='workout'?cards.find(c=>c.id===entry.card_id)?.name||'Saved workout':entry?.kind==='rest'?'Rest day':'Plan this day'}</h3>{entry&&<p className="calendar-state">{calendarStatus(entry,today)}{entry.moved_to?` to ${dateLabel(entry.moved_to)}`:''}</p>}
    {entry?.status==='completed'?<p>This planned session is complete. You can start another saved card as an extra workout.</p>:<>
     <label>Workout<select aria-label="Workout for selected date" value={selectedCard} onChange={e=>setSelectedCard(e.target.value)}><option value="">Rest day</option>{cards.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
     <label>Repeat<select aria-label="Repeat workout" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}>{[1,2,4,8,12].map(n=><option key={n} value={n}>{n===1?'This date only':`Weekly · ${n} weeks`}</option>)}</select></label>
     {weeks>1&&<small>Repeats fill empty dates only. Existing workouts and rest days stay as planned.</small>}
     <button className="primary" disabled={busy||loading} onClick={()=>void act(()=>planner.plan(selected,selectedCard||null,weeks))}>{busy?'Saving…':'Save calendar plan'}</button>
     {entry&&<div className="planner-actions">{entry.status==='planned'&&entry.kind==='workout'&&<button disabled={busy} onClick={()=>void act(()=>planner.skip(entry.id))}>Skip session</button>}<button disabled={busy} onClick={()=>void act(()=>planner.clear(entry.id))}>Clear date</button></div>}
     {entry?.status==='planned'&&entry.kind==='workout'&&<div className="reschedule"><label>Move to an empty date<input aria-label="Reschedule date" type="date" value={moveDate} onChange={e=>setMoveDate(e.target.value)}/></label><button disabled={busy||!moveDate||moveDate===selected} onClick={()=>void act(()=>planner.move(entry.id,moveDate))}>Reschedule</button></div>}
    </>}
   </div><p className="soft-note">Plans repeat only for the number of weeks you choose. Extend them here whenever you need. Your saved cards are always available.</p>
  </section>}
  {detail&&<div className="sheet-backdrop" onClick={()=>setDetail(null)}><section className="sheet workout-detail" role="dialog" aria-modal="true" aria-label={detail.name} onClick={e=>e.stopPropagation()}><div className="sheet-head"><h2>{detail.name}</h2><button aria-label="Close workout details" onClick={()=>setDetail(null)}>×</button></div><div className="workout-detail-scroll"><p>{detail.notes}</p>{detail.items.map((item,i)=><article key={i}><h3>{i+1}. {item.exercise.name}</h3><p>{item.targetSets} × {item.targetReps} · {item.exercise.restSeconds}s rest</p><small>{item.exercise.coachingNotes}</small></article>)}</div><div className="planner-actions"><button onClick={()=>{onEdit(detail);setDetail(null)}}>Edit card</button><button className="primary" onClick={()=>{requestStart(detail);setDetail(null)}}>Start workout</button></div></section></div>}
  {choice&&<div className="sheet-backdrop"><section className="sheet start-choice" role="dialog" aria-modal="true" aria-label="Choose how to start"><div className="sheet-head"><h2>Start {choice.name}?</h2><button aria-label="Cancel start" disabled={busy} onClick={()=>setChoice(null)}>×</button></div><p>Today already has {todayEntry?.kind==='rest'?'a rest day':`“${recommended?.name||'a workout'}”`} planned.</p><button disabled={busy} className="primary" onClick={()=>void act(async()=>{const card=choice;const id=await planner.plan(today,card.id);setChoice(null);onStart(card,{id,scheduled_on:today,card_id:card.id,kind:'workout',status:'planned',moved_to:null})})}>Replace today’s plan</button><button disabled={busy} onClick={()=>{onStart(choice);setChoice(null)}}>Start as an extra workout</button><small>An extra workout leaves your calendar plan unchanged.</small></section></div>}
 </div>;
}
