import type {Exercise} from "./exercise-catalog";
import {additionalExerciseGuides} from "./exercise-guide-library";

export type ExerciseGuide={summary:string;primary:string[];secondary:string[];setup:string[];steps:string[];cues:string[];mistakes:string[];substitutions:string[];image?:string};

const guides:Record<string,ExerciseGuide>={
 "barbell-hip-thrust":{summary:"A loaded hip-extension exercise that keeps the upper back supported while the glutes drive the pelvis upwards.",primary:["Gluteus maximus"],secondary:["Hamstrings","Adductors","Core"],setup:["Place the lower shoulder blades against a stable bench.","Centre a padded barbell across the hip crease.","Plant the feet about hip-width apart where the shins will be close to vertical at the top."],steps:["Brace the trunk and lower the hips under control.","Drive through the whole foot and extend the hips.","Finish with ribs down and the pelvis level, then pause before lowering."],cues:["Chin gently tucked","Push the floor away","Finish with the glutes—not the lower back"],mistakes:["Overextending the lower back","Feet too far forward or too close","Bouncing out of the bottom"],substitutions:["Weighted glute bridge","Dumbbell hip thrust","Cable hip thrust"],image:"./exercise-guides/barbell-hip-thrust.jpg"},
 "romanian-deadlift":{summary:"A controlled hip hinge that loads the glutes and hamstrings while the bar stays close to the legs.",primary:["Hamstrings","Gluteus maximus"],secondary:["Spinal erectors","Adductors","Grip"],setup:["Stand tall with the bar against the thighs and feet about hip-width apart.","Use a secure grip and soften the knees slightly.","Brace before beginning the hinge."],steps:["Send the hips backwards while keeping the bar close to the legs.","Lower only as far as you can maintain a neutral trunk and controlled pelvis.","Drive the hips forward to stand tall without leaning backwards."],cues:["Hips back","Bar brushes the legs","Keep the armpits tight"],mistakes:["Turning the movement into a squat","Letting the bar drift forward","Chasing depth after the back begins to round"],substitutions:["Dumbbell Romanian deadlift","Cable pull through","45-degree back extension"],image:"./exercise-guides/romanian-deadlift.jpg"},
 "glute-biased-bulgarian-split-squat":{summary:"A rear-foot-elevated split squat using a longer stride and modest torso lean to emphasise the working-side glute.",primary:["Gluteus maximus"],secondary:["Quadriceps","Adductors","Hamstrings"],setup:["Stand a comfortable stride in front of a stable bench.","Rest the rear foot lightly on the bench and keep most of the load through the front leg.","Set the front foot so the heel remains planted throughout."],steps:["Lower the rear knee while allowing a controlled forward torso lean.","Keep the front knee tracking in line with the toes.","Drive through the front foot to return to the start."],cues:["Long, stable stance","Sit down and slightly back","Front hip does the work"],mistakes:["Pushing hard through the rear leg","Front knee collapsing inward","Using a stance that is too narrow to balance"],substitutions:["Glute-biased reverse lunge","Smith split squat","Step-up"],image:"./exercise-guides/glute-biased-bulgarian-split-squat.jpg"},
 "seated-leg-curl":{image:"./exercise-guides/seated-leg-curl.jpg",summary:"A knee-flexion exercise that trains the hamstrings in a lengthened seated position.",primary:["Hamstrings"],secondary:["Gastrocnemius"],setup:["Align the machine pivot with the knee joint.","Secure the thigh pad and place the ankle pad just above the heel."],steps:["Brace against the seat and curl the pad down smoothly.","Pause briefly in the shortened position.","Return under control without letting the weight stack crash."],cues:["Hips stay heavy","Curl through the heel","Control the return"],mistakes:["Hips lifting from the seat","Using momentum","Rushing the lengthened position"],substitutions:["Lying leg curl","Nordic hamstring curl","Slider leg curl"]},
 "glute-biased-back-extension":{image:"./exercise-guides/glute-biased-back-extension.jpg",summary:"A hip-extension variation that uses hip movement to bias the glutes rather than lumbar extension.",primary:["Gluteus maximus"],secondary:["Hamstrings","Spinal erectors"],setup:["Set the pad below the hip crease so the hips can move freely.","Turn the feet slightly out and brace the abdomen."],steps:["Fold at the hips under control.","Drive the hips into the pad and squeeze the glutes to rise.","Stop when the body is in line—do not hyperextend."],cues:["Move at the hips","Push hips into the pad","Finish level"],mistakes:["Throwing the torso upwards","Overarching at the top","Placing the pad too high"],substitutions:["Cable pull through","45-degree hip extension","Romanian deadlift"]},
 "cable-kickback":{image:"./exercise-guides/cable-kickback.jpg",summary:"A single-leg cable hip-extension exercise used to train the glute with a stable torso and controlled range.",primary:["Gluteus maximus"],secondary:["Hamstrings","Gluteus medius"],setup:["Attach an ankle cuff and hold the machine for balance.","Stand tall with the working hip slightly flexed and the trunk braced."],steps:["Drive the working leg backwards without rotating the pelvis.","Pause where the glute is fully shortened.","Return slowly without letting the stack pull you forward."],cues:["Square hips","Small controlled arc","Move the thigh, not the spine"],mistakes:["Arching the lower back","Swinging the leg","Opening the pelvis"],substitutions:["Donkey kick","Glute-biased back extension","Single-leg hip thrust"]},
 "hip-abduction-machine":{image:"./exercise-guides/hip-abduction-machine.jpg",summary:"A seated hip-abduction exercise that trains the side glutes by moving the thighs apart against resistance.",primary:["Gluteus medius","Gluteus minimus"],secondary:["Upper gluteus maximus"],setup:["Sit securely with the pads against the outer thighs.","Choose a torso position you can keep still and set a comfortable starting range."],steps:["Press the knees apart smoothly.","Pause without bouncing at the widest controlled position.","Return slowly while keeping tension."],cues:["Pelvis stays still","Lead with the knees","Control both directions"],mistakes:["Bouncing the pads","Using a range that rotates the pelvis","Letting the stack slam"],substitutions:["Cable hip abduction","Banded lateral walk","Side-lying hip abduction"]}
};

// Unknown custom exercises must not display generic text as a completed guide.
export const exerciseGuides:Readonly<Record<string,ExerciseGuide>>={...additionalExerciseGuides,...guides};
export function getExerciseGuide(exercise:Exercise):ExerciseGuide|undefined{return exerciseGuides[exercise.id];}
