import type {ExerciseGuide} from './exercise-guides';

// Explicit movement guides. Shared mechanics are reused only within the same
// movement family; each variation supplies its own setup and execution details.
const list=(text:string)=>text.split('|');
function g(summary:string,primary:string,secondary:string,setup:string,steps:string,cues:string,mistakes:string,substitutions:string):ExerciseGuide{
 return {summary,primary:list(primary),secondary:list(secondary),setup:list(setup),steps:list(steps),cues:list(cues),mistakes:list(mistakes),substitutions:list(substitutions)};
}
const guides:Record<string,ExerciseGuide>={};
function add(id:string,guide:ExerciseGuide){if(guides[id])throw new Error(`Duplicate guide: ${id}`);guides[id]=guide;}

function hipLift(summary:string,setup:string,steps:string){return g(summary,'Gluteus maximus','Hamstrings|Adductors|Abdominals',setup,steps,'Keep ribs over pelvis|Push through the whole foot','Finishing by arching the lower back|Letting the knees collapse inward','Barbell hip thrust|Weighted glute bridge');}
add('dumbbell-hip-thrust',hipLift('A bench supported hip extension with a dumbbell across the hips.','Secure a bench against movement and rest your lower shoulder blades on its edge.|Hold a padded dumbbell across the hip crease with feet flat and knees bent.','Lower your hips while keeping the dumbbell secure.|Press through your feet to bring the hips in line with the torso.|Pause with ribs down, then lower without rolling the dumbbell towards the abdomen.'));
add('cable-hip-thrust',hipLift('A hip thrust against a low cable, using a purpose made belt or padded attachment.','Use a stable bench and a secure hip belt approved for the cable machine; do not balance an unsecured handle on your hips.|Face the low pulley with the attachment across the hip crease and shoulder blades supported.','Take up slack with hips lowered and feet planted.|Extend the hips against the cable while holding your torso steady.|Return slowly, keeping the belt secure and the cable clear of your legs.'));
add('glute-bridge-weighted',hipLift('A floor based hip extension with external load over the hips.','Lie on your back, knees bent and feet flat.|Secure a padded barbell or dumbbell at the hip crease with both hands.','Brace and press your feet into the floor.|Lift until shoulders, hips and knees form a line.|Lower your hips to the floor under control, keeping the load steady.'));
add('single-leg-glute-bridge',hipLift('A floor bridge that trains one hip at a time.','Lie on your back with one foot planted near your hips.|Lift the other foot and keep the pelvis level.','Push through the planted foot to raise your hips.|Stop when the working hip is extended without twisting the pelvis.|Lower slowly and complete the same repetitions on the other side.'));
add('single-leg-hip-thrust',hipLift('A bench supported hip thrust performed on one planted leg.','Rest your shoulder blades on a stable bench.|Plant one foot, lift the opposite foot and square your hips.','Lower your hips while keeping the free leg off the floor.|Drive through the planted foot until the working hip is extended.|Lower without tilting the pelvis; repeat on the other side.'));
add('frog-pump',hipLift('A short range glute bridge with the soles of the feet together.','Lie on your back and bring the soles of your feet together.|Let your knees open only as far as comfortable; keep your neck relaxed.','Brace and lift your pelvis by extending the hips.|Keep the feet together and stop before the lower back arches.|Lower to the floor without bouncing.'));
add('donkey-kick',g('A bent knee hip extension from hands and knees.','Gluteus maximus','Hamstrings|Abdominals','Place hands below shoulders and knees below hips.|Keep one knee bent approximately to a right angle.','Lift that thigh behind you while keeping the pelvis facing the floor.|Stop before your back arches or your hips rotate.|Lower the knee under the hip and repeat on both sides.','Move the thigh, not the spine|Keep your waist still','Kicking high by arching the back|Shifting all your weight to one side','Cable kickback|Single-leg glute bridge'));
add('fire-hydrant',g('A bent knee hip abduction from a kneeling position.','Gluteus medius|Gluteus minimus','Gluteus maximus|Abdominals','Set up on hands and knees with weight evenly supported.|Brace and keep the working knee bent.','Lift the knee out to the side without turning your trunk.|Pause before the pelvis begins to roll open.|Return the knee below the hip and repeat on the other side.','Keep both hips facing down|Use a small controlled arc','Rolling the body to lift higher|Collapsing through the supporting shoulder','Cable abductor|Banded lateral walk'));
add('cable-abductor',g('Standing hip abduction against a low cable.','Gluteus medius|Gluteus minimus','Upper gluteus maximus|Abdominals','Stand side on to a low pulley with a cuff on the outside ankle.|Hold the frame and leave room for the leg to move outwards.','Move the working thigh away from the midline with toes facing forward.|Stop before leaning or hiking the hip.|Return slowly across the starting position and repeat on both sides.','Pelvis stays level|Move from the hip','Leaning away from the pulley|Turning the movement into a kick forward','Hip abduction machine|Banded lateral walk'));
add('banded-lateral-walk',g('Side steps against a resistance band to load the hip abductors.','Gluteus medius|Gluteus minimus','Quadriceps|Gluteus maximus','Place a loop band above the knees or around the ankles.|Adopt a small hip and knee bend with feet pointing ahead.','Take a controlled step sideways without rocking your trunk.|Bring the trailing foot in far enough to reset, maintaining band tension.|Take equal steps in both directions.','Keep knees over feet|Move both feet deliberately','Dragging the trailing foot|Knees falling inward','Cable abductor|Hip abduction machine'));
add('cable-pull-through',g('A hip hinge with a low cable pulling from behind.','Gluteus maximus|Hamstrings','Spinal erectors|Abdominals','Face away from a low pulley, holding a rope between your legs.|Walk forward until the cable is taut and plant feet about shoulder width.','Send the hips backwards with a small knee bend as hands pass between your thighs.|Extend the hips to stand tall while keeping arms relaxed.|Hinge again without squatting down or leaning back.','Hips back then through|Arms act as hooks','Pulling with the arms|Finishing with a backward lean','Romanian deadlift|Glute-biased back extension'));
add('reverse-hyperextension',g('Supported hip extension with the legs moving behind the torso.','Gluteus maximus|Hamstrings','Spinal erectors','Use a stable reverse hyper machine and set the pad at the hip crease.|Secure the ankle attachment if used and hold the handles.','Let the legs lower through a comfortable hip bend.|Raise the thighs until they align with your torso.|Lower slowly without swinging the load or overextending your back.','Keep the torso supported|Stop at body level','Swinging for momentum|Lifting above the torso line','Glute-biased back extension|Cable kickback'));

function squat(summary:string,setup:string,steps:string){return g(summary,'Quadriceps|Gluteus maximus','Adductors|Abdominals|Spinal erectors',setup,steps,'Keep pressure across the whole foot|Knees follow the toes','Heels lifting unintentionally|Losing trunk control at the bottom','Leg press|Goblet squat');}
add('back-squat',squat('A barbell squat with the load supported across the upper back.','Set rack hooks just below shoulder height and safety bars below your planned depth.|Place the bar across the upper traps, take a secure grip and step back into a stable stance.','Brace before bending the hips and knees together.|Lower to a depth you can control with feet flat.|Drive the floor away and stand, then reset your breath before the next repetition.'));
add('front-squat',squat('A squat with the bar resting on the front of the shoulders.','Set the bar in a rack with safeties and rest it across your front deltoids.|Use a clean or crossed arm grip and keep elbows high enough to support the bar.','Brace and bend the knees and hips while keeping the torso upright.|Descend without letting the bar roll forward.|Stand by pushing through your whole foot, maintaining the front rack.'));
add('goblet-squat',squat('A squat holding a dumbbell or kettlebell close to the chest.','Hold the load at chest height with elbows pointing down.|Choose a stance that lets your knees follow the toes.','Sit between your hips while keeping the weight close.|Lower only as far as the heels stay grounded and trunk stays controlled.|Push through both feet to stand without tipping the weight forward.'));
add('sumo-squat',squat('A squat using a wider stance and outward turned toes.','Stand wider than shoulder width with a comfortable toe angle.|Hold a dumbbell or kettlebell securely between the legs.','Bend the hips and knees, keeping knees aligned with your toes.|Lower without forcing your hips wider than comfortable.|Push through both feet to stand, keeping the load close.'));
add('hack-squat',squat('A machine squat with the torso supported by an angled sled.','Set the safety stops and place your back and shoulders against the pads.|Plant feet on the platform and release the handles only when secure.','Bend the knees and hips while keeping your back against the pad.|Lower to a controlled depth without your heels or pelvis lifting.|Extend the legs without snapping the knees, then re-engage the safeties when finished.'));
add('pendulum-squat',squat('A supported squat following the arc of a pendulum machine.','Adjust the stops to a reachable depth and fit your shoulders beneath the pads.|Position your feet so the machine arc allows them to remain fully planted.','Unrack and descend along the machine arc.|Keep the knees tracking with your toes and your back supported.|Drive through the platform to stand; engage the catch before stepping out.'));
add('belt-squat',squat('A squat loaded through a belt around the hips.','Secure the belt over the hips and attach it to the machine as instructed.|Stand centrally on the platform, set the safety stop and use handles for balance.','Release the load and sit down between the hips.|Keep the belt centred while your knees bend along the toes.|Stand through both feet and re-rack the load before unclipping.'));
add('leg-press',g('A supported leg press extending the knees and hips against a sled.','Quadriceps|Gluteus maximus','Adductors','Adjust the seat so your back and pelvis remain supported.|Place feet about shoulder width on the plate, set the stops and unlock the sled.','Lower the sled until just before the pelvis starts to curl off the pad.|Press evenly through both feet to extend the legs.|Keep a controlled knee position and secure the catches before exiting.','Keep the pelvis on the pad|Use the whole foot','Going so deep the lower back lifts|Locking the knees abruptly','Hack squat|Belt squat'));
function lunge(summary:string,setup:string,steps:string,glute=false){return g(summary,glute?'Gluteus maximus':'Quadriceps|Gluteus maximus','Adductors|Hamstrings|Hip stabilisers',setup,steps,'Use a stance with some side to side width|Front knee follows the toes','Losing the front heel contact|Pushing mostly through the rear leg','Reverse lunges|Bulgarian split squat');}
add('walking-lunges',lunge('Alternating forward lunges that travel across the floor.','Choose a clear, level walkway and hold dumbbells at your sides if loading.|Stand tall with enough space between the feet for balance.','Step forward and lower both knees, keeping the front foot flat.|Drive through the front leg and bring the rear leg through.|Step into the next lunge without rushing or letting the knees collapse inward.'));
add('reverse-lunges',lunge('A lunge in which the rear foot steps back and the front leg drives the return.','Stand with feet about hip width apart; use dumbbells if appropriate.|Keep your weight over the leg that will stay in front.','Step one foot back and bend both knees.|Lower the back knee toward the floor while the front heel stays planted.|Push through the front leg to return, then repeat on each side.'));
add('bulgarian-split-squat',lunge('A split squat with the rear foot elevated on a stable bench.','Set a bench at a comfortable rear foot height.|Rest the rear foot lightly on it and place the front foot far enough forward to stay flat.','Bend the front knee and hip while lowering your rear knee.|Keep most of the load on the front leg and avoid twisting the pelvis.|Drive through the front foot to stand and repeat on the other side.'));
add('glute-biased-reverse-lunge',lunge('A reverse lunge with a longer step and slight torso lean to load the front hip.','Hold dumbbells at your sides and establish a stable stance.|Allow a small forward lean from the hips with your spine steady.','Take a comfortable step backwards and lower the rear knee.|Let the front hip flex while keeping the front foot planted.|Drive through the front leg to return without throwing the torso backwards.',true));
add('glute-biased-smith-split-squat',lunge('A stationary split squat under a Smith bar with emphasis on the front hip.','Set the Smith safeties and rest the bar on the upper traps.|Use a longer split stance that fits the rail angle; both feet stay on the floor.','Unrack and lower the back knee while allowing a small forward torso lean.|Keep the front knee tracking over the foot and pelvis square.|Stand through the front leg, then rack securely before changing sides.',true));
add('smith-reverse-lunge',lunge('A reverse lunge performed beneath a guided Smith machine bar.','Set safeties just below your comfortable bottom position and support the bar on the upper traps.|Test the rail angle with a light load and leave space to step backwards.','Unrack, step one foot backwards and lower the rear knee.|Keep the front foot flat and knee tracking over the toes.|Drive through the front leg to return, then rack the bar before changing your setup.'));
add('step-ups',lunge('A single leg step onto a raised platform.','Choose a stable step low enough that your pelvis stays level.|Place the entire working foot on top; hold dumbbells if loading.','Lean slightly over the working foot and push through it to stand on the step.|Bring the trailing foot up lightly without using it to push off the floor.|Lower the trailing foot back to the floor under control and repeat both sides.'));
add('leg-extension',g('A machine knee extension that isolates the quadriceps.','Quadriceps','Hip flexors as stabilisers','Align the knee joint with the machine pivot and support your back.|Place the shin pad above the ankles and adjust the starting bend.','Straighten the knees smoothly while keeping the thighs on the seat.|Pause near full extension without kicking the pad.|Lower slowly to the starting bend.','Keep hips down|Lead with the shin pad','Throwing the weight up|Lifting your hips to finish','Leg press|Goblet squat'));
add('single-leg-romanian-deadlift',g('A hip hinge balancing on one leg while the other leg reaches behind.','Hamstrings|Gluteus maximus','Hip stabilisers|Spinal erectors|Grip','Stand on one foot with the knee softly bent; use a hand support if needed.|Hold a dumbbell in the opposite hand or start without load.','Send the hips back as the free leg reaches behind you.|Keep both hip bones facing the floor and stop before the trunk rounds.|Drive through the planted foot to stand without twisting.','Reach long behind you|Keep hips square','Opening the free hip to the side|Reaching the weight down with a rounded back','Romanian deadlift|Glute-biased back extension'));
function deadlift(summary:string,setup:string,steps:string){return g(summary,'Gluteus maximus|Quadriceps|Hamstrings','Spinal erectors|Trapezius|Grip',setup,steps,'Keep the bar close|Push the floor away','Jerking a slack bar from the floor|Leaning backwards at lockout','Romanian deadlift|Rack pull');}
add('conventional-deadlift',deadlift('A barbell lift from the floor using coordinated hip and knee extension.','Position the bar over midfoot with feet about hip width.|Grip outside the legs, brace the trunk and take the slack out of the bar.','Push through the floor so hips and shoulders rise together.|Keep the bar close as you extend your hips and knees to stand.|Hinge to lower the bar, then bend the knees once it passes them; reset on the floor.'));
add('sumo-deadlift',deadlift('A floor deadlift with a wide stance and the hands inside the knees.','Choose a comfortable wide stance with toes turned out and shins near the bar.|Grip between the legs, brace and align your knees with your toes.','Take up slack and push the floor away while keeping the bar close.|Extend the knees and hips together to stand tall.|Lower under control and reset without letting the knees collapse inward.'));
add('rack-pull',deadlift('A partial deadlift from rack pins with a shortened starting range.','Set equal pin heights around just below the knees and place the bar on them.|Stand with the bar close, grip securely and brace before pulling.','Push through the floor and extend the hips to stand.|Keep the bar close without shrugging or leaning backwards.|Hinge to return the bar gently to both pins and reset.'));
add('good-morning',g('A barbell hip hinge with the load across the upper back.','Hamstrings|Gluteus maximus','Spinal erectors|Abdominals','Use a light bar in a rack with safety bars set below the planned range.|Rest it securely on the upper traps and soften the knees.','Brace and push the hips backwards while the torso tips forwards.|Stop while your spine and pelvis remain controlled.|Extend the hips to stand without leaning back.','Move through the hips|Keep the load modest','Turning the hinge into a squat|Going deeper than trunk control allows','Romanian deadlift|Cable pull through'));
add('lying-leg-curl',g('Prone machine knee flexion for the hamstrings.','Hamstrings','Gastrocnemius','Lie face down with knees aligned to the machine pivot.|Set the ankle pad above the heels and hold the handles.','Curl your heels toward your hips while keeping the pelvis on the pad.|Pause without lifting the hips.|Extend the knees slowly without slamming the stack.','Hips stay on the pad|Curl smoothly','Arching the back to finish|Kicking the pad with momentum','Seated leg curl|Nordic hamstring curl'));
add('nordic-hamstring-curl',g('A demanding kneeling hamstring exercise that resists the body falling forwards.','Hamstrings','Gluteus maximus|Abdominals','Kneel on a pad with ankles held by a purpose made anchor or reliable partner.|Keep hips extended and hands ready to catch your weight; use band assistance if needed.','Lower your whole body forwards from the knees as slowly as you can.|Catch yourself with your hands before losing control.|Use your hands or assistance to return and reset your hip position.','Stay long from knees to head|Use assistance early','Folding at the hips|Falling without a controlled catch','Seated leg curl|Lying leg curl'));
add('hip-adduction-machine',g('Seated hip adduction bringing the thighs together against resistance.','Hip adductors','Pelvic stabilisers','Set the pads against the inner thighs and select a comfortable open position.|Keep your back and pelvis supported.','Bring the thighs together smoothly without twisting the knees.|Pause before the pads meet forcefully.|Let the legs open slowly without forcing a stretch.','Move both thighs evenly|Keep pelvis still','Starting wider than comfortable|Slamming the pads together','Sumo squat|Sumo deadlift'));
function calf(summary:string,setup:string,steps:string,primary:string){return g(summary,primary,'Foot and ankle stabilisers',setup,steps,'Rise through the big toe side without rolling the ankle|Pause at both ends','Bouncing at the bottom|Rolling onto the outside of the foot','Standing calf raise|Seated calf raise');}
add('standing-calf-raise',calf('A calf raise with the knees mostly straight.','Use a standing calf machine or hold a weight with a hand support.|Place the balls of the feet securely on the edge, with heels free.','Lower your heels into a comfortable stretch while keeping knees softly straight.|Rise onto the balls of the feet as high as controlled.|Pause, then lower without bouncing.','Gastrocnemius|Soleus'));
add('seated-calf-raise',calf('A calf raise with bent knees to emphasise the soleus.','Sit with the thigh pad secure above your knees.|Set the balls of the feet on the platform and release the lever.','Lower your heels while keeping the feet aligned.|Lift the heels against the thigh pad and pause.|Lower slowly and re-rack the lever before exiting.','Soleus'));
add('single-leg-calf-raise',calf('A calf raise on one supporting leg.','Hold a stable support and place the ball of one foot on a step.|Keep the other foot clear and the working knee softly straight.','Lower the working heel under control.|Push up through the forefoot without leaning or rolling the ankle.|Pause and lower, then complete the other side.','Gastrocnemius|Soleus'));

function row(summary:string,setup:string,steps:string){return g(summary,'Latissimus dorsi|Rhomboids|Middle trapezius','Rear deltoids|Biceps|Grip',setup,steps,'Lead with the elbows|Let the shoulder blades move with control','Jerking the torso to move the weight|Shrugging towards the ears','Chest-supported row|Seated cable row');}
add('chest-supported-row',row('A row with the chest supported to limit lower back loading.','Adjust the bench or chest pad so the arms can reach freely.|Plant your feet and take a comfortable grip without lifting the chest.','Draw your elbows back while keeping your chest on the support.|Pause as the handles approach your ribs.|Reach forward under control without collapsing your shoulders.'));
add('machine-chest-supported-row',row('A chest supported row using a guided machine lever.','Adjust the seat so the handles line up with the lower chest.|Keep the sternum against the pad and feet planted.','Pull the handles back with your elbows while keeping the torso supported.|Stop before the shoulders roll forward at the finish.|Return the handles slowly until the arms are extended.'));
add('barbell-bent-over-row',row('A barbell row while holding a braced hip hinge.','Grip the bar slightly wider than your legs and hinge at the hips.|Keep knees softly bent and the trunk at an angle you can hold still.','Pull the bar toward the lower ribs without standing up.|Keep elbows moving behind the body and wrists straight.|Lower to long arms while maintaining the same hip hinge.'));
add('one-arm-dumbbell-row',row('A unilateral row with a dumbbell and bench support.','Support one hand on a stable bench and plant your feet or support one knee.|Keep your back steady and hold a dumbbell below the working shoulder.','Draw the elbow back toward your hip without twisting your chest upwards.|Pause with the dumbbell near the lower ribs.|Lower to a controlled reach and repeat on the other side.'));
add('seated-cable-row',row('A horizontal cable row from a seated position.','Place feet on the platform with knees slightly bent.|Sit tall, grasp the handle and take up cable tension.','Pull the handle toward the lower ribs without rocking backwards.|Allow the shoulder blades to come together naturally.|Reach forward through the shoulders while keeping the lower back controlled.'));
add('t-bar-row',row('A row using a T-bar or landmine lever between the legs.','Secure the bar in its landmine or use a purpose made T-bar machine.|Set your grip and hip hinge; use the chest pad if the machine provides one.','Row the handles toward the lower chest without lifting your torso.|Pause with elbows behind your body.|Lower along the lever arc until the arms lengthen.'));
add('machine-row',row('A seated row against a machine resistance path.','Adjust the seat so the handles sit around lower chest height.|Plant both feet and keep any chest support firmly in contact.','Pull the handles backwards without leaning away from the seat.|Bring the elbows behind the body through a comfortable range.|Return slowly without letting the weight stack crash.'));
add('meadows-row',row('A one arm landmine row from a stance beside the end of a barbell.','Secure the bar in a landmine and stand side on near its loaded end.|Hinge at the hips, support your free forearm on your thigh and grip the sleeve.','Row the bar end towards your outer ribs with the elbow moving back and out.|Keep the pelvis stable rather than rotating to lift the load.|Lower with control and repeat on the opposite side.'));
add('single-arm-cable-lat-row',row('A one arm cable row with the elbow kept near the torso to emphasise the lat.','Set a single handle around lower chest height and face the pulley.|Use a staggered stance or seated support and reach the working arm forward.','Pull your elbow towards the same-side hip with your torso facing the pulley.|Stop before the shoulder rolls forward or your trunk twists.|Let the arm reach forwards slowly and repeat on the other side.'));
add('machine-high-row',row('A machine row pulling down and back from high handles.','Adjust the seat so the high handles can be reached without lifting off it.|Secure your chest against the pad and take a firm grip.','Draw the elbows down and back towards your sides.|Keep the torso supported as the handles approach your upper ribs.|Return up the machine arc without shrugging abruptly.'));
function pulldown(summary:string,setup:string,steps:string){return g(summary,'Latissimus dorsi|Teres major','Biceps|Lower trapezius|Rhomboids',setup,steps,'Drive elbows towards your ribs|Keep the torso mostly still','Swinging backwards to start the pull|Pulling behind the neck','Lat pulldown|Assisted pull-ups');}
add('lat-pulldown',pulldown('An overhead cable pull to the front of the chest.','Secure your thighs beneath the pad and grip the bar just outside shoulder width.|Sit tall with a small backward lean and arms overhead.','Draw the elbows down as the bar travels towards the upper chest.|Stop at a comfortable position in front of you without forcing contact.|Return to long arms with controlled shoulder movement.'));
add('close-grip-pulldown',pulldown('A pulldown with a close neutral handle.','Attach a close grip handle and secure your thighs.|Sit tall with the handle above you and palms facing each other.','Pull the elbows down beside your ribs as the handle approaches the chest.|Keep the chest lifted without leaning far backwards.|Allow the arms to extend overhead slowly.'));
add('neutral-grip-lat-pulldown',pulldown('A pulldown using parallel handles and palms facing one another.','Fit a neutral grip attachment and adjust the thigh restraint.|Sit with arms overhead, wrists straight and feet planted.','Pull the handles down towards the upper chest by bringing the elbows towards your sides.|Keep your ribs controlled rather than arching to reach lower.|Return overhead through a comfortable shoulder range.'));
add('single-arm-pulldown',pulldown('A unilateral overhead cable pull.','Attach a single handle to a high pulley.|Sit or kneel facing it with the working arm reaching up and pelvis square.','Pull the elbow down towards the same-side ribs.|Keep your trunk upright without bending sideways.|Reach overhead slowly and repeat on the other arm.'));
add('straight-arm-pulldown',g('A cable shoulder extension with only a small fixed elbow bend.','Latissimus dorsi|Teres major','Triceps long head|Abdominals','Hold a bar or rope on a high pulley and step back.|Use a slight hip hinge and keep elbows softly bent.','Sweep the arms down towards the thighs without turning it into an elbow extension.|Pause with the ribs down and shoulders controlled.|Return the arms forward and up without arching the back.','Keep the elbow angle nearly fixed|Pull from the armpits','Bending the elbows into a pressdown|Rocking your torso','Single-arm pulldown|Cable pull-over variation'));
function pullup(summary:string,setup:string,steps:string){return g(summary,'Latissimus dorsi|Teres major','Biceps|Rhomboids|Lower trapezius|Grip',setup,steps,'Bring elbows down towards the ribs|Use a controlled lowering phase','Kicking for momentum|Reaching the chin forward instead of lifting the body','Assisted pull-ups|Lat pulldown');}
add('pull-ups',pullup('An overhead bodyweight pull using an overhand grip.','Grip a secure overhead bar slightly wider than shoulder width.|Start from a controlled hang with a braced trunk and legs still.','Pull your body up by driving the elbows down.|Lift as high as you can without craning your neck or swinging.|Lower to a comfortable long-arm position and reset.'));
add('chin-ups',pullup('An overhead bodyweight pull using palms facing you.','Hold a secure overhead bar around shoulder width with an underhand grip.|Hang with your trunk braced and legs quiet.','Pull your chest towards the bar with elbows moving down beside you.|Avoid thrusting the chin forward to finish.|Lower slowly to a comfortable arm extension.'));
add('assisted-pull-ups',pullup('A pull-up with a machine or band reducing the load.','Use the machine steps and knee or foot support as designed, or anchor a suitable band securely.|Choose enough assistance to control the entire repetition.','Pull the elbows down to lift your torso without swinging.|Pause near the top while keeping the neck relaxed.|Lower smoothly; use the steps to exit the machine or remove the band carefully.'));
add('inverted-row',g('A bodyweight horizontal pull beneath a fixed bar.','Rhomboids|Middle trapezius|Latissimus dorsi','Biceps|Rear deltoids|Abdominals','Secure a bar in a rack at a height suited to your strength.|Hang beneath it with heels planted and body held in a straight line; bend knees to make it easier.','Pull your chest towards the bar while keeping your hips aligned.|Pause without jutting the chin or arching the back.|Lower your torso slowly until the arms are long.','Move as one piece|Bring chest to bar','Hips sagging|Bouncing to finish','Seated cable row|Chest-supported row'));
add('face-pulls',g('A rope cable pull towards the face with shoulder external rotation.','Rear deltoids|Middle trapezius|Rhomboids','Shoulder external rotators|Biceps','Set a rope around upper chest to eye height.|Step back with arms extended and brace in a stable stance.','Pull the rope towards your forehead while separating the ends.|Let elbows travel out and bring hands near the sides of your head without forcing rotation.|Return slowly to long arms.','Hands separate as you pull|Keep the load light enough for rotation','Leaning back to shift the load|Shrugging and forcing the shoulders','Reverse pec deck|Rear delt fly'));
add('barbell-shrug',g('A loaded elevation of the shoulder blades.','Upper trapezius|Levator scapulae','Grip|Trunk stabilisers','Stand tall with a barbell held in front of the thighs.|Keep your neck neutral and arms straight.','Lift your shoulders upwards without rolling them.|Pause while keeping the elbows straight.|Lower the shoulders slowly to the starting position.','Lift straight up|Keep neck relaxed','Rolling the shoulders in circles|Bending the arms to lift the bar','Dumbbell shrug variation|Loaded carry'));

function press(summary:string,setup:string,steps:string){return g(summary,'Pectoralis major','Anterior deltoids|Triceps',setup,steps,'Keep wrists stacked over forearms|Use a controlled shoulder range','Bouncing off the chest|Flaring the elbows straight out to the sides','Dumbbell bench press|Machine chest press');}
add('barbell-bench-press',press('A horizontal barbell press from a flat bench.','Set rack safeties or use a spotter and position eyes beneath the racked bar.|Plant your feet and settle the shoulder blades against the bench.','Unrack and lower the bar towards the mid to lower chest with forearms near vertical.|Touch lightly if comfortable, without bouncing.|Press back up while keeping your hips on the bench and rack only when stable.'));
add('dumbbell-bench-press',press('A flat bench press with independently moving dumbbells.','Sit with dumbbells supported on your thighs, then guide them into place as you lie back.|Plant your feet and keep the shoulder blades supported.','Lower the dumbbells beside the chest with elbows comfortably below shoulder level.|Press up and slightly inward without clashing the weights.|Lower slowly; bring the weights back to your thighs when finishing.'));
add('incline-barbell-bench-press',press('A barbell chest press on an incline bench, increasing emphasis on the upper pectorals.','Set a modest bench incline and position the rack and safeties accordingly.|Plant feet and grip so the forearms remain roughly vertical near the bottom.','Lower the bar towards the upper chest without flaring the elbows widely.|Press up while keeping your shoulders supported and hips down.|Return slowly and re-rack securely.'));
add('incline-dumbbell-press',press('An incline dumbbell press for the chest with more upper chest emphasis.','Set the bench to a comfortable moderate incline.|Bring dumbbells beside the upper chest with feet firmly planted.','Lower the weights with elbows below shoulder level.|Press upwards without shrugging or hitting the dumbbells together.|Return under control while keeping the torso against the bench.'));
add('low-incline-dumbbell-press',press('A dumbbell press on a low incline to train the chest with a small upward angle.','Set the bench around 15–30 degrees and bring dumbbells into position.|Keep feet planted and shoulder blades supported.','Lower the weights to either side of the upper chest.|Press up and slightly inward with wrists over elbows.|Lower smoothly while maintaining the same bench contact.'));
add('decline-bench-press',press('A chest press from a modestly declined bench.','Use a bench with secure leg restraints and a spotter or appropriate rack safeties.|Fix your legs and grip the bar comfortably before unracking.','Lower the bar towards the lower chest without bouncing.|Press upwards along a controlled path.|Rack the bar fully before releasing the leg restraints.'));
add('machine-chest-press',press('A seated chest press against a guided machine path.','Adjust the seat so handles align around mid chest.|Keep feet grounded and back against the pad.','Press the handles forward while keeping wrists aligned.|Stop short of a forceful elbow lockout.|Return until the upper arms reach a comfortable chest stretch.'));
add('smith-machine-bench-press',press('A bench press using a guided Smith bar.','Centre a flat bench so the rail path brings the bar to the chest comfortably.|Set safeties above the chest and check the path with a light load.','Unlock the bar and lower it slowly towards the chest.|Press along the rails with shoulders supported.|Rotate the bar into its hooks only after it is stable.'));
function fly(summary:string,setup:string,steps:string){return g(summary,'Pectoralis major','Anterior deltoids|Biceps as stabilisers',setup,steps,'Keep a small fixed elbow bend|Bring the upper arms together','Turning the fly into a press|Reaching so far back the shoulder loses control','Pec deck|Cable chest fly');}
add('cable-chest-fly',fly('A standing cable fly bringing the arms together at chest height.','Set pulleys around chest height and hold one handle in each hand.|Step forward into a staggered stance with elbows softly bent.','Sweep both arms forwards in a wide arc.|Bring hands together in front of the chest without rounding the shoulders.|Open the arms slowly to a comfortable stretch while keeping the same elbow bend.'));
add('low-to-high-cable-fly',fly('An upward cable fly with greater emphasis on the upper chest.','Set both pulleys low and hold the handles beside and slightly behind your hips.|Stand in a stable staggered stance with chest lifted.','Sweep the arms forwards and upwards towards upper chest height.|Bring the handles together without shrugging or leaning back.|Return down the same arc under control.'));
add('high-to-low-cable-fly',fly('A downward cable fly from high pulleys.','Set both pulleys above shoulder height.|Step forwards with handles wide, elbows softly bent and trunk braced.','Bring the arms down and forwards towards the lower chest or upper abdomen.|Keep the elbow bend steady as the hands approach one another.|Return up and out without letting the cable pull the shoulders too far back.'));
add('cable-crossover',fly('A cable fly with a small crossover at the front if comfortable.','Set pulleys near shoulder height and stand between them in a staggered stance.|Begin with elbows softly bent and arms open in a comfortable range.','Bring the hands together in front of the chest.|Allow a small crossover without twisting the trunk, alternating which hand crosses above.|Open slowly, keeping shoulders controlled.'));
add('pec-deck',fly('A supported machine fly bringing the upper arms towards the midline.','Adjust the seat so the handles or pads are near chest height.|Set the starting range so the shoulders are not pulled far behind the torso.','Bring the arms or pads together in front of the chest.|Pause while keeping the back on the pad.|Open slowly until you reach a comfortable chest stretch.'));
add('dumbbell-fly',fly('A flat bench fly with dumbbells moving through an arc.','Lie on a flat bench with light dumbbells above the chest.|Plant feet and bend elbows slightly.','Open the arms out to the sides until upper arms are around torso level or earlier if needed.|Bring the upper arms together above the chest without changing elbow bend substantially.|Lower along the same controlled arc.'));
function pushup(summary:string,setup:string,steps:string){return g(summary,'Pectoralis major|Triceps','Anterior deltoids|Abdominals|Serratus anterior',setup,steps,'Keep ribs and hips moving together|Allow the shoulder blades to move','Hips sagging|Elbows pointing straight sideways','Machine chest press|Incline push-up variation');}
add('push-ups',pushup('A bodyweight press from a straight arm plank.','Place hands slightly wider than shoulders and extend the legs.|Brace your abdomen and glutes so your body forms a straight line; elevate hands if needed.','Lower the chest towards the floor with elbows angling back.|Stop before your hips sag or shoulders lose control.|Press the floor away to return to straight arms.'));
add('deficit-push-ups',pushup('A push-up with hands elevated on secure handles to allow extra depth.','Use stable equal height handles or platforms and establish a straight body position.|Choose a small deficit that your shoulders comfortably tolerate.','Lower your chest between the handles without sagging through the trunk.|Stop at a controlled shoulder range rather than chasing the deepest position.|Press evenly through both handles to rise.'));
function dip(summary:string,setup:string,steps:string){return g(summary,'Triceps|Pectoralis major','Anterior deltoids|Scapular stabilisers',setup,steps,'Keep shoulders controlled|Use assistance to preserve form','Dropping too deeply into the shoulders|Bouncing from the bottom','Close-grip bench press|Tricep pushdown');}
add('chest-dips',dip('A parallel bar dip with a small forward torso lean.','Use parallel bars with steps or an assistance machine.|Support your weight with arms straight and choose a comfortable grip width.','Lean the torso slightly forward and bend the elbows.|Lower only through a controlled shoulder range, without forcing the upper arms far behind you.|Press the bars down to return and use the steps to exit.'));
add('tricep-dips',dip('An upright parallel bar dip with emphasis on elbow extension.','Use secure parallel bars or an assisted dip machine.|Start supported above the bars with trunk mostly upright.','Bend the elbows while keeping them close enough for comfortable shoulders.|Stop at a depth you can reverse without collapsing into the shoulders.|Extend the elbows to return; use assistance if bodyweight is too demanding.'));

function shoulderPress(summary:string,setup:string,steps:string){return g(summary,'Anterior deltoids|Lateral deltoids','Triceps|Upper trapezius|Serratus anterior',setup,steps,'Keep ribs over pelvis|Let the shoulder blades rotate upward','Excessive lower back arch|Forcing an uncomfortable overhead range','Machine shoulder press|Dumbbell shoulder press');}
add('barbell-overhead-press',shoulderPress('A standing barbell press from the shoulders overhead.','Set the bar at upper chest height in a rack.|Grip just outside shoulder width and brace with feet planted.','Press upwards, moving your head just enough to clear the bar.|Finish with the bar balanced above the shoulders without leaning back.|Lower to the upper chest while keeping forearms under the bar.'));
add('dumbbell-shoulder-press',shoulderPress('A seated dumbbell overhead press.','Set the bench near upright and keep feet planted.|Hold dumbbells at shoulder height with elbows slightly forward of the torso.','Press overhead through a comfortable range.|Avoid clashing the weights or lifting your ribs to finish.|Lower slowly to shoulder level with forearms near vertical.'));
add('machine-shoulder-press',shoulderPress('A seated overhead press along a machine lever path.','Adjust the seat until the handles start around shoulder height.|Keep your back supported and choose a comfortable grip.','Press the handles upwards without pushing your head forward.|Extend the elbows smoothly without snapping them straight.|Return to shoulder height or your comfortable starting position.'));
add('arnold-press',shoulderPress('A dumbbell shoulder press with gradual forearm rotation.','Sit against a near upright bench with light dumbbells in front of the shoulders.|Start with palms facing you and elbows forward.','Press upwards while gently rotating so palms face forwards near the top.|Use only the rotation range your shoulders tolerate.|Lower and reverse the rotation smoothly to the starting position.'));
add('landmine-press',shoulderPress('An angled one arm press using a securely anchored barbell.','Anchor the bar in a landmine and hold its end at one shoulder.|Adopt a staggered stance or half kneeling position facing the anchor.','Press the end up and forwards along the bar arc.|Reach through the shoulder without rotating your trunk or arching your back.|Lower to the shoulder and repeat on the other side.'));
function raise(summary:string,setup:string,steps:string,primary='Lateral deltoids'){return g(summary,primary,'Supraspinatus|Trapezius|Serratus anterior',setup,steps,'Lead with the upper arms|Use a load that allows a smooth arc','Swinging the torso|Forcing height beyond a comfortable shoulder range','Cable lateral raise|Machine lateral raise');}
add('lateral-raise',raise('A dumbbell raise out to the sides for the lateral deltoids.','Stand with light dumbbells at your sides and elbows softly bent.|Hold arms slightly forward of the body rather than directly to the sides.','Raise the upper arms to around shoulder height or a comfortable lower point.|Keep wrists neutral and allow natural shoulder blade motion.|Lower slowly without resting or swinging the weights.'));
add('cable-lateral-raise',raise('A one arm lateral raise against a low cable.','Attach a single handle to a low pulley and stand side on.|Hold the handle in the outside hand with a slight elbow bend.','Lift the arm out and slightly forwards to around shoulder height.|Keep the torso still and wrist in line with the forearm.|Lower smoothly across the starting position and repeat both sides.'));
add('machine-lateral-raise',raise('A supported lateral raise against machine pads.','Adjust the seat so the machine pivot is near shoulder height.|Place the arms against the pads with a comfortable elbow bend.','Press the upper arms outwards and upwards through the machine arc.|Pause near shoulder height without hiking the shoulders.|Lower the pads slowly without letting the stack drop.'));
add('front-raise',raise('A raise in front of the body for the anterior deltoids.','Stand with light dumbbells in front of your thighs.|Keep the elbows slightly bent and trunk braced.','Lift the arms forwards to around shoulder height.|Avoid leaning back as the weights rise.|Lower to the thighs slowly.','Anterior deltoids'));
add('lu-raise',raise('A light plate raise that continues from the sides towards overhead.','Hold small weight plates at your sides with a secure grip.|Stand tall and begin without heavy loading.','Raise the arms out and up, allowing the shoulder blades to rotate naturally.|Continue overhead only if comfortable, bringing the plates towards each other.|Lower along the same arc without forcing the shoulders or arching your back.','Lateral deltoids|Anterior deltoids'));
add('upright-row',g('An upright pull with a comfortable grip and limited shoulder range.','Lateral deltoids|Upper trapezius','Biceps','Hold a cable bar or barbell in front of the thighs with a moderately wide grip.|Stand tall and keep wrists relaxed rather than bent sharply.','Lift the elbows outwards as the bar travels close to your torso.|Stop with elbows around or below shoulder height, earlier if uncomfortable.|Lower slowly without shrugging or jerking.','Comfort determines the height|Keep elbows below a forced end range','Using a very narrow grip that strains wrists|Pulling high through shoulder pain','Lateral raise|Cable lateral raise'));
function rearFly(summary:string,setup:string,steps:string){return g(summary,'Posterior deltoids','Rhomboids|Middle trapezius',setup,steps,'Sweep arms wide|Keep the elbow bend nearly fixed','Swinging the torso|Turning the movement into a heavy row','Reverse pec deck|Rear delt fly');}
add('rear-delt-fly',rearFly('A bent over or chest supported fly for the rear shoulders.','Use light dumbbells and hinge forward or lie chest down on an incline bench.|Let the arms hang with elbows softly bent and neck neutral.','Sweep the arms out to the sides until roughly in line with the torso.|Keep the chest still and avoid shrugging.|Lower slowly to the hanging position.'));
add('reverse-pec-deck',rearFly('A supported machine reverse fly for the rear deltoids.','Face the chest pad and adjust the seat so handles sit near shoulder height.|Hold the handles with a slight elbow bend.','Open the arms out and back without lifting your chest off the pad.|Stop when the upper arms are around the torso line.|Return slowly to the front without rounding forcefully.'));

function curl(summary:string,setup:string,steps:string,primary='Biceps brachii'){return g(summary,primary,'Brachialis|Brachioradialis',setup,steps,'Keep the upper arm controlled|Lower as deliberately as you lift','Swinging the hips to start|Bending the wrists to finish','Cable bicep curl|Dumbbell bicep curl');}
add('barbell-bicep-curl',curl('A standing elbow curl with a straight bar.','Grip the bar with palms forwards around shoulder width.|Stand with elbows by your sides and trunk braced.','Bend the elbows to bring the bar towards the front of the shoulders.|Stop before the elbows swing far forwards.|Lower until the arms are nearly straight without relaxing the grip.'));
add('ez-bar-curl',curl('A two arm curl using the angled grips of an EZ-bar.','Choose the angled grip that keeps your wrists comfortable.|Stand tall with the bar at your thighs and elbows beside the torso.','Curl the bar up without leaning backwards.|Pause while keeping the upper arms mostly still.|Lower smoothly to long arms.'));
add('dumbbell-bicep-curl',curl('A simultaneous dumbbell curl with palms facing forwards.','Stand or sit with one dumbbell in each hand.|Keep elbows near your sides and palms facing forwards.','Curl both dumbbells by bending the elbows.|Keep shoulders relaxed and wrists straight.|Lower both weights slowly to the starting position.'));
add('alternating-dumbbell-curl',curl('A dumbbell curl performed one arm at a time.','Stand with dumbbells at your sides and a stable trunk.|Start with palms forwards or rotate gently as you curl.','Curl one dumbbell without twisting your torso.|Lower it under control before curling the other arm.|Alternate sides while keeping both shoulders quiet.'));
add('hammer-curl',curl('A dumbbell curl with the palms facing each other.','Hold dumbbells beside your thighs in a neutral grip.|Keep elbows by the ribs and wrists straight.','Bend the elbows to bring the weights towards the shoulders without rotating the grip.|Pause without lifting the shoulders.|Lower slowly to the starting position.','Brachialis|Brachioradialis|Biceps brachii'));
add('incline-dumbbell-curl',curl('A seated curl with the upper arms hanging slightly behind the torso.','Set a moderately inclined bench and sit back with light dumbbells.|Let arms hang naturally without forcing the shoulders backwards.','Curl with palms forwards while keeping the upper arms in place.|Stop before the elbows lift away from their starting position.|Lower slowly to a comfortable elbow extension.'));
add('preacher-curl',curl('An elbow curl with the upper arms supported on a preacher pad.','Adjust the seat so the upper arms rest on the pad without shrugging.|Take a comfortable grip on an EZ-bar, dumbbells or machine handles.','Curl while keeping the upper arms against the pad.|Pause near the top without lifting off the seat.|Lower slowly and avoid snapping into a straight elbow under load.'));
add('cable-bicep-curl',curl('A standing curl against a low cable.','Attach a handle or bar to the low pulley.|Stand facing it with cable tension and elbows near your sides.','Curl towards the shoulders without leaning away from the machine.|Keep wrists straight at the top.|Lower slowly until the elbows are nearly extended.'));
add('bayesian-cable-curl',curl('A one arm cable curl with the upper arm slightly behind the torso.','Set a low pulley behind you and hold its handle in one hand.|Step forwards into a stable stance with a small, comfortable shoulder extension.','Curl the hand towards the shoulder while keeping the upper arm quiet.|Avoid turning the chest or pulling the elbow forwards.|Lower slowly and repeat on the opposite side.'));
add('concentration-curl',curl('A seated one arm curl with the elbow braced against the inner thigh.','Sit on a bench with feet apart and lean forwards from the hips.|Support the working upper arm against the inner thigh and hold a dumbbell palm forwards.','Curl the weight without shifting the elbow support.|Pause near the shoulder while keeping the wrist straight.|Lower slowly and repeat on the other arm.'));
function triceps(summary:string,setup:string,steps:string){return g(summary,'Triceps brachii','Shoulder and trunk stabilisers',setup,steps,'Keep the upper arms stable|Move through the elbows','Swinging the shoulders to shift the load|Forcing or snapping the elbows straight','Tricep pushdown|Cable overhead extension');}
add('tricep-pushdown',triceps('A high cable elbow extension with the upper arms at the sides.','Attach a bar to a high pulley and face the machine.|Hold the bar with elbows bent and upper arms beside your ribs.','Straighten the elbows to press the bar down towards your thighs.|Pause without forcing the shoulders forwards.|Let the elbows bend slowly while keeping the upper arms still.'));
add('rope-tricep-pushdown',triceps('A triceps pressdown using a rope attachment.','Hold both rope ends on a high pulley with palms facing inward.|Keep elbows close to your sides and a stable stance.','Extend the elbows to move the rope towards the thighs.|Let the ends separate naturally without twisting your wrists aggressively.|Return the hands upwards under control without lifting the upper arms.'));
add('skull-crushers',triceps('A lying elbow extension using an EZ-bar or dumbbells.','Lie on a flat bench with a light load above the upper chest.|Keep upper arms angled slightly towards your head and use a spotter when needed.','Bend the elbows to lower the load beside or just behind the head, keeping it clear of your face.|Extend the elbows without moving the shoulders excessively.|Repeat with a slow, controlled lowering phase.'));
add('overhead-tricep-extension',triceps('An overhead dumbbell extension training the triceps at a raised arm position.','Sit supported or stand braced and hold one dumbbell securely overhead with both hands.|Choose a shoulder position that allows the upper arms to remain comfortable.','Bend the elbows to lower the dumbbell behind your head.|Extend the elbows without arching the lower back.|Lower again slowly, keeping the weight securely held.'));
add('cable-overhead-extension',triceps('An overhead elbow extension using a cable rope.','Face away from the pulley and bring the rope behind your head.|Use a split stance and upper arms raised in a comfortable position.','Extend the elbows to move the rope forwards and upwards.|Keep the ribs down and upper arms mostly still.|Let the elbows bend slowly to bring the rope behind the head again.'));
add('dumbbell-kickback',triceps('An elbow extension with the upper arm held beside the torso in a hip hinge.','Hinge at the hips and support your free hand on a bench.|Lift the working upper arm alongside your torso with elbow bent and a light dumbbell held.','Straighten the elbow until the forearm aligns with the upper arm.|Pause without lifting the shoulder or swinging the weight.|Bend the elbow slowly and repeat on the other side.'));
add('close-grip-bench-press',g('A barbell bench press with a moderately narrow grip to emphasise elbow extension.','Triceps brachii','Pectoralis major|Anterior deltoids','Use a rack with safeties or a spotter and plant your feet on the floor.|Take a grip around shoulder width; avoid placing hands so close that wrists bend.','Lower the bar towards the lower chest with elbows near the torso.|Press back up while keeping wrists above forearms.|Lower with control and re-rack when stable.','Keep a comfortable grip width|Maintain bench contact','Hands too close together|Bouncing the bar off the chest','Tricep pushdown|Machine chest press'));
add('wrist-curl',g('A supported wrist flexion for the forearm flexors.','Wrist flexors','Finger flexors','Sit with forearms supported on your thighs or a bench, palms up.|Let the hands extend beyond the support with a light bar or dumbbells.','Lower the hands through comfortable wrist extension.|Curl the palms towards the forearms without lifting your elbows.|Lower slowly while keeping the load securely gripped.','Move only at the wrists|Use a light load','Lifting the forearms|Letting the weight roll out of the fingers','Reverse wrist curl|Suitcase carry'));
add('reverse-wrist-curl',g('A supported wrist extension for the forearm extensors.','Wrist extensors','Finger extensors','Support the forearms on a bench or thighs with palms facing down.|Hold a very light load with the hands beyond the edge.','Raise the knuckles by extending the wrists without lifting the forearms.|Pause in a comfortable range.|Lower the hands slowly without forcing a deep bend.','Keep forearms still|Lift the knuckles','Using too much weight|Jerking through the wrists','Wrist curl|Suitcase carry'));

add('plank',g('A static trunk exercise resisting the lower back sagging.','Rectus abdominis|Transversus abdominis','Obliques|Glutes|Shoulder stabilisers','Place forearms on the floor with elbows below shoulders.|Extend the legs and support yourself on toes; use knees down if needed.','Brace the abdomen and squeeze the glutes to align shoulders, hips and ankles.|Breathe steadily while holding the position.|End the hold when you cannot keep the pelvis and ribs aligned.','Push the floor away|Keep breathing','Hips sagging or lifting high|Holding your breath for the whole set','Dead bug|Incline plank variation'));
add('side-plank',g('A lateral trunk hold resisting sideways bending.','Obliques|Quadratus lumborum','Gluteus medius|Shoulder stabilisers','Lie on one side with elbow below shoulder and legs extended or knees bent for an easier version.|Keep shoulders and hips stacked.','Lift the pelvis until the body forms a straight line.|Hold while breathing and keeping the upper hip from rolling forwards.|Lower with control and repeat on the other side.','Stack hips and shoulders|Press through the forearm','Shoulder collapsing|Twisting the pelvis','Suitcase carry|Pallof press'));
add('cable-crunch',g('A kneeling loaded trunk curl against a high cable.','Rectus abdominis','Obliques','Kneel facing a high pulley with a rope held near the temples.|Keep the hips in a steady position and begin with the trunk gently extended.','Curl the ribcage towards the pelvis without pulling with your arms.|Pause as the abdomen shortens.|Uncurl slowly while keeping the hips from rocking forwards and backwards.','Ribs move towards hips|Hands hold the rope still','Bowing only at the hips|Pulling the rope down with the arms','Machine crunch|Reverse crunch'));
add('machine-crunch',g('A machine assisted trunk curl against resistance.','Rectus abdominis','Obliques','Adjust the seat and chest or shoulder pad according to the machine instructions.|Plant the feet and choose a light starting resistance.','Bring the ribcage towards the pelvis by curling the trunk.|Avoid driving with the arms or pulling your head forward.|Return slowly until the abdomen lengthens comfortably.','Curl through the trunk|Keep neck relaxed','Using arms to move the machine|Rushing the return','Cable crunch|Reverse crunch'));
add('hanging-leg-raise',g('A hanging hip flexion with a pelvic curl at the top.','Hip flexors|Rectus abdominis','Obliques|Grip|Shoulder stabilisers','Hang from a secure bar with shoulders controlled and legs quiet.|Begin with bent knees if straight legs cause swinging or back arching.','Lift the knees or legs forwards, then gently curl the pelvis towards the ribs.|Pause without swinging the body.|Lower slowly until the legs are beneath you and reset.','Start without momentum|Curl the pelvis at the top','Swinging for height|Dropping the legs uncontrollably','Captain’s chair knee raise|Reverse crunch'));
add('captain-s-chair-knee-raise',g('A supported knee raise using forearm pads and a backrest.','Hip flexors|Rectus abdominis','Obliques|Shoulder stabilisers','Climb onto the station steps and place your forearms securely on the pads.|Keep your back supported and shoulders away from your ears.','Raise the knees towards your chest, adding a small pelvic curl.|Pause without throwing your feet forwards.|Lower slowly and use the steps to dismount.','Press into the pads|Lift knees without swinging','Shrugging into the shoulders|Arching away from the back pad','Hanging leg raise|Reverse crunch'));
add('ab-wheel-rollout',g('An anti-extension exercise rolling the arms forwards while resisting a back arch.','Rectus abdominis|Transversus abdominis','Latissimus dorsi|Shoulder stabilisers','Kneel on a pad and grip the wheel beneath the shoulders.|Brace with ribs down; use a wall as a distance stop if learning.','Roll forwards only as far as you can maintain the trunk position.|Keep the hips and shoulders moving together rather than letting the waist sag.|Pull the wheel back beneath you while staying braced.','Shorten the range before the back arches|Move as one unit','Rolling beyond trunk control|Sitting back with the hips to avoid the return','Plank|Dead bug'));
add('russian-twist',g('A seated trunk rotation performed through a small controlled range.','Obliques','Rectus abdominis|Hip flexors','Sit with knees bent and heels on the floor.|Lean back slightly with the spine long; hold hands together or use a light weight.','Turn your ribs and shoulders gently to one side while keeping the pelvis quiet.|Return through centre and rotate to the other side.|Keep the range comfortable without forcing the lower back.','Rotate the ribs, not just the hands|Keep heels supported','Rounding and twisting aggressively|Throwing a heavy weight side to side','Pallof press|Side plank'));
add('dead-bug',g('A supine coordination exercise resisting back extension while opposite limbs reach away.','Transversus abdominis|Rectus abdominis','Obliques|Hip flexors','Lie on your back with arms up and hips and knees bent around 90 degrees.|Exhale gently to settle the ribs and hold a comfortable low back position.','Reach one arm overhead and the opposite heel towards the floor.|Stop before your back arches away from its starting position.|Return both limbs and alternate sides slowly.','Reach only as far as you can brace|Keep breathing','Letting ribs flare|Moving faster than trunk control allows','Plank|Bird dog'));
add('bird-dog',g('A hands and knees exercise extending opposite limbs without rotating the trunk.','Spinal stabilisers|Gluteus maximus','Abdominals|Shoulder stabilisers','Place hands under shoulders and knees under hips.|Keep the spine neutral and weight evenly supported.','Reach one arm forward and the opposite leg backwards.|Pause with hips square and limbs around torso height.|Return under control and alternate sides.','Reach long rather than high|Balance the pelvis','Arching the back to lift the leg|Rocking from side to side','Dead bug|Plank'));
add('pallof-press',g('A cable or band press resisting trunk rotation.','Obliques|Transversus abdominis','Glutes|Shoulder stabilisers','Set a cable at chest height or securely anchor a band.|Stand side on, hold the handle at the sternum and brace in a stable stance.','Press both hands straight forwards while resisting the pull to rotate.|Pause with the chest and pelvis still facing ahead.|Bring the hands back slowly and repeat facing the other direction.','Keep hips and ribs square|Press directly away from the chest','Turning towards the anchor|Leaning to counterbalance too much load','Side plank|Suitcase carry'));
add('reverse-crunch',g('A supine abdominal curl that lifts the pelvis towards the ribcage.','Rectus abdominis','Obliques|Hip flexors','Lie on your back with hips and knees bent.|Rest arms beside you and settle the ribs.','Gently curl the pelvis so the tailbone lifts a little from the floor.|Keep the knee angle fairly steady rather than kicking the feet overhead.|Lower the pelvis slowly and reset without arching the back.','Lift the tailbone a little|Use the abdomen, not momentum','Throwing legs overhead|Rolling onto the neck','Dead bug|Cable crunch'));
add('bicycle-crunch',g('An alternating trunk curl and rotation with opposite knee movement.','Rectus abdominis|Obliques','Hip flexors','Lie on your back with hands lightly beside the head.|Raise the knees and gently lift the shoulder blades from the floor.','Turn one shoulder towards the opposite knee as the other leg extends.|Keep the movement slow and shorten the leg reach if the back arches.|Alternate sides without pulling your head forward.','Turn the shoulder towards the knee|Keep neck relaxed','Yanking the neck|Pedalling too fast to control the trunk','Reverse crunch|Dead bug'));
add('suitcase-carry',g('A one sided loaded carry resisting sideways trunk bending.','Obliques|Quadratus lumborum','Grip|Glutes|Trapezius','Pick up a dumbbell or kettlebell beside one leg with a controlled hinge.|Stand tall with shoulders and hips level and a clear walking route.','Walk with short controlled steps without leaning towards or away from the load.|Maintain normal breathing and a firm grip.|Set the weight down carefully, then repeat on the other side.','Stay tall and level|Keep steps smooth','Leaning to offset the weight|Holding a load too heavy to walk steadily','Side plank|Pallof press'));

function cardio(summary:string,primary:string,setup:string,steps:string,cues:string,mistakes:string,substitutions:string){return g(summary,primary,'Cardiovascular system|Trunk stabilisers',setup,steps,cues,mistakes,substitutions);}
add('outdoor-running',cardio('Continuous running outdoors at a pace suited to the session.','Quadriceps|Glutes|Hamstrings|Calves','Choose a clear route with suitable footwear and footing.|Begin with walking and easy jogging before increasing pace.','Run with relaxed shoulders and comfortable steps landing near your centre of mass.|Build speed gradually while keeping breathing controlled for the intended effort.|Slow to an easy jog or walk to finish.','Keep steps relaxed|Look ahead along the route','Overstriding to force speed|Starting hard without warming up','Treadmill run|Stationary bike'));
add('treadmill-run',cardio('Running on a motorised treadmill with adjustable speed and incline.','Quadriceps|Glutes|Hamstrings|Calves','Attach the safety clip and locate the stop control.|Start with the belt slow and increase from a walk.','Run near the middle of the belt with relaxed arms rather than holding the rails.|Adjust speed gradually so you can maintain natural steps.|Reduce speed to a walk and stop the belt before stepping off.','Stay centred on the belt|Use the safety clip','Jumping onto a fast belt|Hanging on the handrails at an excessive speed','Outdoor running|Elliptical'));
add('stationary-bike',cardio('Seated cycling against adjustable resistance.','Quadriceps|Glutes','Set the saddle so the knee remains slightly bent at the bottom of the pedal stroke.|Adjust handlebars to a comfortable reach and secure feet as designed.','Pedal smoothly through each revolution without rocking the hips.|Choose resistance and cadence that match the planned effort.|Reduce resistance and pedal easily before stopping.','Keep knees tracking forwards|Relax your grip','Seat too low or high|Grinding a resistance that disrupts pedalling','Assault bike|Elliptical'));
add('rowing-machine',cardio('Coordinated leg drive, hip movement and arm pull on an indoor rower.','Quadriceps|Glutes|Latissimus dorsi','Adjust footplates and straps across the widest part of the feet.|Use a manageable resistance and start with knees bent, arms long and a forward hip hinge.','Push with the legs, then open the hips and draw the handle to the lower ribs.|Send the arms away first, hinge forwards, then bend the knees to return.|Keep the recovery smooth and avoid pulling early with the arms.','Drive with the legs first|Recover arms, hips, then knees','Bending arms before the leg drive|Rounding the lower back at the catch','Stationary bike|Ski erg'));
add('stairmaster',cardio('Stepping on a moving staircase for sustained conditioning.','Quadriceps|Glutes|Calves','Locate the emergency stop and begin at a slow speed.|Step on with a secure handhold, then stand tall once balanced.','Place as much of the foot on each step as the machine allows.|Step steadily without hanging your bodyweight on the rails.|Slow and stop the machine before stepping off.','Stand over your feet|Use rails lightly for balance','Leaning heavily on the rails|Skipping steps before you can control the pace','Step-ups|Incline treadmill walking'));
add('elliptical',cardio('Continuous stepping through an elliptical pedal path.','Quadriceps|Glutes|Hamstrings','Step onto the stopped pedals using the fixed supports.|Choose low resistance and a stride setting that feels natural.','Move the pedals smoothly while keeping feet in contact.|Use moving handles if comfortable and stay upright rather than hanging on them.|Slow gradually until the pedals stop before dismounting.','Keep hips level|Match resistance to smooth movement','Bouncing through the torso|Stopping or stepping off moving pedals abruptly','Stationary bike|Treadmill run'));
add('ski-erg',cardio('A double pole ski motion using a standing cable ergometer.','Latissimus dorsi|Triceps|Abdominals','Stand facing the machine with feet about shoulder width.|Hold the handles with elbows softly bent and hands near forehead height.','Initiate the pull with the trunk and a hip hinge, adding a small knee bend.|Finish with the handles beside the thighs, extending the elbows.|Rise smoothly and return the hands upwards to reset.','Use the trunk as well as the arms|Keep the cable path smooth','Pulling only with the arms|Squatting deeply on every stroke','Rowing machine|Assault bike'));
add('assault-bike',cardio('Fan bike conditioning using coordinated pedalling and moving handles.','Quadriceps|Glutes|Shoulders|Arms','Adjust the seat so the knee stays slightly bent at full pedal reach.|Grip the handles and begin with easy pedalling.','Coordinate pushing and pulling the handles with smooth leg drive.|Build effort gradually; the fan resistance rises as you move faster.|Ease down progressively before releasing the moving handles and stopping.','Match arms and legs|Keep the torso steady','Starting a maximal effort without preparation|Rocking violently to increase output','Stationary bike|Rowing machine'));
add('jump-rope',cardio('Repeated small hops timed with a rope turning under the feet.','Calves|Foot muscles','Choose a clear area and a rope length that clears your body.|Hold the handles near the hips with elbows close to the sides.','Turn the rope mainly from the wrists and make small hops just high enough to clear it.|Land softly with knees slightly bent and an upright trunk.|Pause and reset when timing or landing control breaks down.','Small quiet hops|Turn from the wrists','Jumping unnecessarily high|Landing stiffly or continuing through ankle pain','Stationary bike|Low impact step intervals'));
add('hiit-sprints',cardio('Short fast running intervals separated by recovery periods.','Glutes|Hamstrings|Quadriceps|Calves','Choose a clear level route and plan enough space to slow down.|Warm up with easy running and progressive accelerations before the intervals.','Accelerate gradually to the planned fast pace rather than straining from the first step.|Slow down over several steps after each effort, then walk or jog for recovery.|Stop the fast intervals when coordination or speed clearly deteriorates.','Stay relaxed at speed|Leave space to decelerate','Abrupt maximal starts without warming up|Forcing more repetitions with failing technique','Assault bike intervals|Stationary bike intervals'));

function jump(summary:string,setup:string,steps:string){return g(summary,'Gluteus maximus|Quadriceps|Calves','Hamstrings|Trunk stabilisers',setup,steps,'Land quietly with hips and knees bending|Reset fully between jumps','Continuing after jump quality falls|Landing with stiff knees or knees collapsing inward','Countermovement jump when appropriate|Coached low impact power work');}
add('countermovement-jump',jump('An explosive bodyweight jump using a quick dip before take-off.','Use a clear, non-slip space with room overhead.|Only use jumping when you can take off and land comfortably and any relevant injury restrictions allow it.','Dip briefly through the hips and knees and swing the arms naturally.|Push rapidly through both feet to jump straight upwards.|Land softly with knees following the toes, settle your balance and reset before the next jump.'));
add('trap-bar-jump',jump('A lightly loaded vertical jump holding a trap bar; this is advanced power work.','Use a light load chosen with a qualified coach, a clear landing area and secure collars.|Stand centred inside the bar, pick it up with a braced trunk and keep arms long.','Dip a small amount and drive through both feet to jump vertically without curling the arms.|Land with the bar held steadily and hips and knees bending to absorb the landing.|Regain balance and reset fully; stop when speed or landing control falls.'));

export const additionalExerciseGuides=guides;
